#include <runtime/production.hpp>
#include <algorithm>
#include <queue>
#include <thread>
namespace rebuntu::runtime::production {
std::optional<std::vector<std::string>> Initializer::startup_order(const std::vector<Dependency>& ds){std::map<std::string,int> deg;std::map<std::string,std::vector<std::string>> out;for(auto&d:ds)deg[d.id]=0;for(auto&d:ds)for(auto&r:d.dependencies){if(!deg.count(r))continue;++deg[d.id];out[r].push_back(d.id);}std::queue<std::string>q;for(auto&[k,v]:deg)if(v==0)q.push(k);std::vector<std::string>o;while(!q.empty()){auto n=q.front();q.pop();o.push_back(n);for(auto&x:out[n])if(--deg[x]==0)q.push(x);}if(o.size()!=deg.size())return std::nullopt;return o;}
InitResult Initializer::initialize(RuntimeContext c,const std::vector<Dependency>&ds)const{c.lifecycle=LifecycleState::kInitializing;auto order=startup_order(ds);if(!order)return {core::Outcome::failure("E_DEP_CYCLE","runtime dependency cycle"),std::move(c),"dependencies"};for(auto&id:*order){auto it=std::find_if(ds.begin(),ds.end(),[&](auto&d){return d.id==id;});if(it!=ds.end()&&it->required&&!it->ready)return {core::Outcome::failure("E_DEP_NOT_READY","required dependency not ready: "+id),std::move(c),id};}c.lifecycle=LifecycleState::kReady;c.readiness=ReadinessState::kReady;return {core::Outcome::success(true),std::move(c),std::nullopt};}
bool Resolver::add_operation(core::OperationDefinition op){if(op.id.empty()||operations_.count(op.id))return false;operations_.emplace(op.id,std::move(op));return true;}
ResolutionResult Resolver::resolve(const core::OperationRequest&r)const{auto it=operations_.find(r.operation_id);if(it==operations_.end())return {ResolutionStatus::kNotFound,std::nullopt,{"operation not found"}};ResolvedWork w;w.operation=it->second;if(!it->second.provider_ids.empty()){if(providers_){infrastructure::ProviderSelectionContext c;c.capability=r.operation_id;auto s=providers_->select(c);if(!s.provider)return {ResolutionStatus::kUnavailable,std::nullopt,s.rejected};w.provider_id=s.provider->id;}else w.provider_id=it->second.provider_ids.front();}return {ResolutionStatus::kResolved,w,{}};}
bool Dispatcher::register_handler(std::string c,Handler h){if(c.empty()||!h||handlers_.count(c))return false;handlers_.emplace(std::move(c),std::move(h));return true;}
core::Outcome Dispatcher::dispatch(const core::OperationRequest&r,const ResolvedWork&w,CancellationToken&t)const{if(t.is_cancelled())return core::Outcome::cancelled("cancelled before dispatch");auto it=handlers_.find(w.operation.id);if(it==handlers_.end())return core::Outcome::failure("E_NO_HANDLER","no execution handler for "+w.operation.id);return it->second(r,w,t);}
static bool bad(const core::Outcome&o){return o.status==core::SemanticStatus::kFailure||o.status==core::SemanticStatus::kCancelled||o.status==core::SemanticStatus::kUnknown;}
core::Outcome OperationPipeline::run(const core::OperationRequest&r,CancellationToken&t,const OperationHooks&h)const{auto rr=resolver_.resolve(r);if(rr.status!=ResolutionStatus::kResolved||!rr.work)return core::Outcome::failure("E_RESOLUTION","operation resolution failed");if(t.is_cancelled())return core::Outcome::cancelled("cancelled");if(h.observe_before){auto o=h.observe_before(r);if(bad(o))return o;}if(h.authorize){auto o=h.authorize(r);if(bad(o))return o;}if(r.dry_run)return core::Outcome::completed();auto o=dispatcher_.dispatch(r,*rr.work,t);if(bad(o))return o;if(h.observe_after){auto a=h.observe_after(r);o.evidence.insert(o.evidence.end(),a.evidence.begin(),a.evidence.end());if(bad(a))return a;}if(h.verify){auto v=h.verify(r);o.evidence.insert(o.evidence.end(),v.evidence.begin(),v.evidence.end());if(v.status==core::SemanticStatus::kSuccess&&v.verified){o.status=core::SemanticStatus::kSuccess;o.verified=true;}else return v;}return o;}
core::Outcome Engine::submit(const core::OperationRequest&r,const OperationHooks&h){if(!accepting_||context_.readiness!=ReadinessState::kReady)return core::Outcome::failure("E_NOT_READY","runtime not accepting work");return pipeline_.run(r,*context_.cancellation,h);}
core::Outcome JobRuntime::run(JobRecord&rec,const std::function<core::Outcome(int)>&fn,CancellationToken&t)const{int max=rec.job.max_attempts?std::max(1,rec.job.max_attempts->value):1;for(int i=1;i<=max;++i){if(t.is_cancelled()){rec.final_outcome=core::Outcome::cancelled("job cancelled");return *rec.final_outcome;}auto o=fn(i);rec.attempts.push_back({i,o});if(o.status==core::SemanticStatus::kSuccess||o.status==core::SemanticStatus::kCompleted){rec.final_outcome=o;return o;}}rec.final_outcome=rec.attempts.back().outcome;return *rec.final_outcome;}
std::optional<Activation> ActivationGate::activate(const Event&e,std::string trigger,core::OperationRequest r,size_t max){std::lock_guard l(mu_);std::string key=e.id+":"+trigger;if(seen_.count(key)||inflight_>=max)return std::nullopt;seen_.insert(key);++inflight_;return Activation{key,e.id,std::move(trigger),std::move(r)};}
void ActivationGate::complete(const std::string&){std::lock_guard l(mu_);if(inflight_)--inflight_;}
bool Coordinator::acquire(const std::string&r,const std::string&o){std::lock_guard l(mu_);auto [it,ok]=owners_.emplace(r,o);return ok||it->second==o;}void Coordinator::release(const std::string&r,const std::string&o){std::lock_guard l(mu_);auto it=owners_.find(r);if(it!=owners_.end()&&it->second==o)owners_.erase(it);}
core::Outcome ShutdownCoordinator::shutdown(Engine&e,std::vector<std::shared_ptr<CancellationToken>> ts,std::chrono::milliseconds grace){e.stop_admission();e.context().lifecycle=LifecycleState::kStopping;for(auto&t:ts)if(t)t->cancel();if(grace.count()>0)std::this_thread::sleep_for(std::min(grace,std::chrono::milliseconds(5)));e.context().cancellation->cancel();e.context().readiness=ReadinessState::kNotReady;e.context().lifecycle=LifecycleState::kStopped;return core::Outcome::success(true);}
RecoveryClassification classify_recovery(const work::ExecutionRecord&r,bool alive){if(r.completed_at)return RecoveryClassification::kCompleted;if(alive)return RecoveryClassification::kStillRunning;if(r.outcome.status==core::SemanticStatus::kSuccess&&!r.outcome.verified)return RecoveryClassification::kRequiresVerification;if(r.outcome.status==core::SemanticStatus::kUnknown)return RecoveryClassification::kUnknown;return RecoveryClassification::kInterrupted;}
}
