#pragma once
#include "reconciliation/domain_reconciler.hpp"
#include "profiles.hpp"
#include <stdexcept>
namespace rebuntu::domains::common {
struct DomainSemantics { DomainProfile profile; std::vector<OperationRuleV2> operations; std::vector<std::string> health_keys; };
inline DomainSemantics service_semantics(){return {service_profile(),{{"active_state","active","start","systemd",true,{},"stop","systemd"},{"active_state","inactive","stop","systemd",true,{},"start","systemd"},{"unit_file_state","enabled","enable","systemd",true,{},"disable","systemd"},{"unit_file_state","disabled","disable","systemd",true,{},"enable","systemd"}},{"active_state","load_state"}};}
inline DomainSemantics process_semantics(){return {process_profile(),{{"state","stopped","terminate","procfs",true,{{"__verify_mode","absent_or_equals"}}},{"state","running","continue","procfs",true,{{"__verify_mode","present"}}}},{"state"}};}
inline DomainSemantics storage_semantics(){return {storage_profile(),{{"mounted","true","mount","filesystems",true,{},"unmount","filesystems"},{"mounted","false","unmount","filesystems",true,{},"mount","filesystems"}},{"mounted","usage_percent"}};}
inline DomainSemantics networking_semantics(){return {networking_profile(),{{"link_state","up","up","netlink",true,{},"down","netlink"},{"link_state","down","down","netlink",true,{},"up","netlink"},{"address_present","true","add_address","netlink",true,{},"remove_address","netlink"},{"address_present","false","remove_address","netlink",true,{},"add_address","netlink"}},{"link_state","carrier"}};}
inline DomainSemantics software_semantics(){return {software_profile(),{{"installed","true","install","package-manager",true,{},"remove","package-manager"},{"installed","false","remove","package-manager",true,{},"install","package-manager"},{"version_state","latest","upgrade","package-manager"}},{"installed"}};}
inline DomainSemantics configuration_semantics(){return {configuration_profile(),{{"content_state","desired","write","filesystem/native-owner",true,{},"restore","filesystem/native-owner"},{"content_state","previous","restore","filesystem/native-owner",true,{},"write","filesystem/native-owner"}},{"content_state"}};}
inline DomainSemantics identity_semantics(){return {identity_profile(),{}, {"resolved"}};}
inline DomainSemantics accelerator_semantics(){return {accelerator_profile(),{{"workload_placement","requested","place_workload","linux-driver/sysfs"}},{"available","driver_bound"}};}
inline DomainSemantics semantics_for(const std::string& kind){if(kind=="service")return service_semantics();if(kind=="process")return process_semantics();if(kind=="storage")return storage_semantics();if(kind=="network")return networking_semantics();if(kind=="package")return software_semantics();if(kind=="configuration")return configuration_semantics();if(kind=="identity")return identity_semantics();if(kind=="accelerator")return accelerator_semantics();throw std::invalid_argument("unknown domain kind: "+kind);}
inline Health assess_attributes(const core::Entity& e,const DomainSemantics& s){Health h;for(const auto& key:s.health_keys){auto i=e.attributes.find(key);HealthSignal sig;sig.name=key;sig.evidence=core::Evidence{"domain-observation",s.profile.authority,i==e.attributes.end()?"<missing>":i->second,std::chrono::system_clock::now()};if(i==e.attributes.end()){sig.status="degraded";sig.detail="missing authoritative attribute";}else if(i->second=="failed"||i->second=="error"||i->second=="unavailable"){sig.status="failed";sig.detail=i->second;}else{sig.status="healthy";sig.detail=i->second;}h.signals.push_back(std::move(sig));}return h;}
}
