# CMake generated Testfile for 
# Source directory: /home/bvrznski/rebuntu/cpp/tests
# Build directory: /home/bvrznski/rebuntu/cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_packages]=] "/home/bvrznski/rebuntu/cpp/tests/test_packages")
set_tests_properties([=[test_packages]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;63;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[install_planning_test]=] "/home/bvrznski/rebuntu/cpp/tests/install_planning_test")
set_tests_properties([=[install_planning_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;91;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[runtime_runner_test]=] "/home/bvrznski/rebuntu/cpp/tests/runtime_runner_test")
set_tests_properties([=[runtime_runner_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;109;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[automation_test]=] "/home/bvrznski/rebuntu/cpp/tests/automation_test")
set_tests_properties([=[automation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;110;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_runtime_contracts]=] "/home/bvrznski/rebuntu/cpp/tests/test_runtime_contracts")
set_tests_properties([=[test_runtime_contracts]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;111;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_state_provider]=] "/home/bvrznski/rebuntu/cpp/tests/test_state_provider")
set_tests_properties([=[test_state_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;112;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[events_test]=] "/home/bvrznski/rebuntu/cpp/tests/events_test")
set_tests_properties([=[events_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;113;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[results_test]=] "/home/bvrznski/rebuntu/cpp/tests/results_test")
set_tests_properties([=[results_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;114;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_discovery]=] "/home/bvrznski/rebuntu/cpp/tests/test_discovery")
set_tests_properties([=[test_discovery]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;115;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[settings_test]=] "/home/bvrznski/rebuntu/cpp/tests/settings_test")
set_tests_properties([=[settings_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;116;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[config_test]=] "/home/bvrznski/rebuntu/cpp/tests/config_test")
set_tests_properties([=[config_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;117;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[preferences_test]=] "/home/bvrznski/rebuntu/cpp/tests/preferences_test")
set_tests_properties([=[preferences_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;118;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[structured_setup_test]=] "/home/bvrznski/rebuntu/cpp/tests/structured_setup_test")
set_tests_properties([=[structured_setup_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;127;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[profile_test]=] "/home/bvrznski/rebuntu/cpp/tests/profile_test")
set_tests_properties([=[profile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;137;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[user_identity_test]=] "/home/bvrznski/rebuntu/cpp/tests/user_identity_test")
set_tests_properties([=[user_identity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;146;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[capability_state_test]=] "/home/bvrznski/rebuntu/cpp/tests/capability_state_test")
set_tests_properties([=[capability_state_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;155;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[group_membership_test]=] "/home/bvrznski/rebuntu/cpp/tests/group_membership_test")
set_tests_properties([=[group_membership_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;164;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[ownership_test]=] "/home/bvrznski/rebuntu/cpp/tests/ownership_test")
set_tests_properties([=[ownership_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;173;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[lifecycle_test]=] "/home/bvrznski/rebuntu/cpp/tests/lifecycle_test")
set_tests_properties([=[lifecycle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;182;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[host_foundation_test]=] "/home/bvrznski/rebuntu/cpp/tests/host_foundation_test")
set_tests_properties([=[host_foundation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;194;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_scope]=] "/home/bvrznski/rebuntu/cpp/tests/test_scope")
set_tests_properties([=[test_scope]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;203;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_sessions]=] "/home/bvrznski/rebuntu/cpp/tests/test_sessions")
set_tests_properties([=[test_sessions]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;212;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_secrets]=] "/home/bvrznski/rebuntu/cpp/tests/test_secrets")
set_tests_properties([=[test_secrets]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;217;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_directories]=] "/home/bvrznski/rebuntu/cpp/tests/test_directories")
set_tests_properties([=[test_directories]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;226;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_locks]=] "/home/bvrznski/rebuntu/cpp/tests/test_locks")
set_tests_properties([=[test_locks]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;235;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_ipc]=] "/home/bvrznski/rebuntu/cpp/tests/test_ipc")
set_tests_properties([=[test_ipc]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;244;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_temp_files]=] "/home/bvrznski/rebuntu/cpp/tests/test_temp_files")
set_tests_properties([=[test_temp_files]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;253;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[semantic_provider_test]=] "/home/bvrznski/rebuntu/cpp/tests/semantic_provider_test")
set_tests_properties([=[semantic_provider_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;263;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[subprocess_executor_test]=] "/home/bvrznski/rebuntu/cpp/tests/subprocess_executor_test")
set_tests_properties([=[subprocess_executor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;273;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[semantic_service_test]=] "/home/bvrznski/rebuntu/cpp/tests/semantic_service_test")
set_tests_properties([=[semantic_service_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;287;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_ipc_protocol]=] "/home/bvrznski/rebuntu/cpp/tests/test_ipc_protocol")
set_tests_properties([=[test_ipc_protocol]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;300;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[infrastructure_test]=] "/home/bvrznski/rebuntu/cpp/tests/infrastructure_test")
set_tests_properties([=[infrastructure_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;309;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_container_runtime]=] "/home/bvrznski/rebuntu/cpp/tests/test_container_runtime")
set_tests_properties([=[test_container_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;323;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_docker_provider]=] "/home/bvrznski/rebuntu/cpp/tests/test_docker_provider")
set_tests_properties([=[test_docker_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;337;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_ansible_provider]=] "/home/bvrznski/rebuntu/cpp/tests/test_ansible_provider")
set_tests_properties([=[test_ansible_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;351;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_jenkins_provider]=] "/home/bvrznski/rebuntu/cpp/tests/test_jenkins_provider")
set_tests_properties([=[test_jenkins_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;367;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[test_pipeline_provider]=] "/home/bvrznski/rebuntu/cpp/tests/test_pipeline_provider")
set_tests_properties([=[test_pipeline_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;381;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[dispatcher_test]=] "/home/bvrznski/rebuntu/cpp/tests/dispatcher_test")
set_tests_properties([=[dispatcher_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;391;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[controller_test]=] "/home/bvrznski/rebuntu/cpp/tests/controller_test")
set_tests_properties([=[controller_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;405;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[resolver_test]=] "/home/bvrznski/rebuntu/cpp/tests/resolver_test")
set_tests_properties([=[resolver_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;418;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[coordination_test]=] "/home/bvrznski/rebuntu/cpp/tests/coordination_test")
set_tests_properties([=[coordination_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;432;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[loader_test]=] "/home/bvrznski/rebuntu/cpp/tests/loader_test")
set_tests_properties([=[loader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;442;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[unit_executor_test]=] "/home/bvrznski/rebuntu/cpp/tests/unit_executor_test")
set_tests_properties([=[unit_executor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;461;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
add_test([=[workflow_test]=] "/home/bvrznski/rebuntu/cpp/tests/workflow_test")
set_tests_properties([=[workflow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;477;add_test;/home/bvrznski/rebuntu/cpp/tests/CMakeLists.txt;0;")
