#include "domains/common/saturation.hpp"
#include <cassert>
#include <iostream>
using namespace rebuntu; using namespace rebuntu::domains::common;
static security::policy::AuthorizeMutation allow_all=[](const core::NativeOperation&,const security::policy::AuthorizationContext& c){return security::policy::AuthorizationResult{security::policy::Decision::allow,"test",c.plan_fingerprint};};
int main(){
 {DomainProfile p{"service","systemd",{{"mutation",{"set"},{}}}};std::vector<OperationRuleV2> rules{{"mode","ready","set","systemd",true,{{"__verify_equals.health","ok"},{"__verify_min.score","90"},{"__verify_max.latency","20"}}}};core::Entity state{"s","service",{{"mode","old"},{"health","bad"},{"score","0"},{"latency","99"},{"generation","1"}}, {}};DomainReconciler r(p,rules);ReconcileOptions o;o.authorize=allow_all;o.native_generation_attribute="generation";auto obs=[&](const std::string&)->std::optional<core::Entity>{return state;};auto ex=[&](const core::NativeOperation& op){state.attributes[op.arguments.at("attribute")]=op.arguments.at("desired");state.attributes["health"]="ok";state.attributes["score"]="95";state.attributes["latency"]="10";state.attributes["generation"]="2";return true;};auto out=r.reconcile({"s",{{"mode","ready"}},"rich"},obs,ex,{},o);assert(out.converged&&out.operation_evidence.size()==3);for(auto&e:out.operation_evidence)assert(e.passed&&e.operation_index==0);}
 std::cout<<"RICH_MULTI_PREDICATE_VERIFICATION_PASS\n";
 {DomainProfile p{"service","systemd",{{"mutation",{"set"},{}}}};std::vector<OperationRuleV2> rules{{"a","1","set","systemd"},{"b","1","set","systemd"}};core::Entity state{"s","service",{{"a","0"},{"b","0"},{"generation","1"}}, {}};DomainReconciler r(p,rules);ReconcileOptions o;o.authorize=allow_all;o.native_generation_attribute="generation";int observations=0,execs=0;auto obs=[&](const std::string&)->std::optional<core::Entity>{++observations;if(execs==1&&observations>=5)state.attributes["generation"]="external";return state;};auto ex=[&](const core::NativeOperation& op){++execs;state.attributes[op.arguments.at("attribute")]=op.arguments.at("desired");state.attributes["generation"]=std::to_string(execs+1);return true;};auto rb=[](const core::NativeOperation&){return true;};auto out=r.reconcile({"s",{{"a","1"},{"b","1"}},"cas"},obs,ex,rb,o);assert(!out.converged&&execs==1&&out.rolled_back);}
 std::cout<<"PER_OPERATION_CAS_STALE_PLAN_REJECTION_PASS\n";
 {DomainProfile p{"service","systemd",{{"mutation",{"set"},{}}}};std::vector<OperationRuleV2> rules{{"mode","ready","set","systemd",true,{{"__verify_min.score","90"}}}};core::Entity state{"s","service",{{"mode","old"},{"score","not-a-number"}}, {}};DomainReconciler r(p,rules);ReconcileOptions o;o.authorize=allow_all;o.guard_pre_execution_drift=false;o.guard_each_operation_drift=false;auto obs=[&](const std::string&)->std::optional<core::Entity>{return state;};auto ex=[&](const core::NativeOperation& op){state.attributes[op.arguments.at("attribute")]=op.arguments.at("desired");return true;};auto out=r.reconcile({"s",{{"mode","ready"}},"numeric fail closed"},obs,ex,{},o);assert(!out.converged&&!out.operation_evidence.empty()&&!out.operation_evidence[0].passed);}
 std::cout<<"MALFORMED_NATIVE_METRIC_FAIL_CLOSED_PASS\n";
}
