# CMake generated Testfile for 
# Source directory: /home/bvrznski/rebuntu/cpp
# Build directory: /home/bvrznski/rebuntu/cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[context_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-context-test")
set_tests_properties([=[context_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;139;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[procfs_process_integration_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-procfs-process-integration-test")
set_tests_properties([=[procfs_process_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;668;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[systemd_service_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-systemd-service-test")
set_tests_properties([=[systemd_service_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;794;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[sysfs_device_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-sysfs-device-test")
set_tests_properties([=[sysfs_device_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;802;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cpu_topology_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cpu-topology-test")
set_tests_properties([=[cpu_topology_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;876;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[exit_result_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-exit-result-test")
set_tests_properties([=[exit_result_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1031;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[idempotency_classifier_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-idempotency-test")
set_tests_properties([=[idempotency_classifier_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1039;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[retry_mechanics_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-retry-mechanics-test")
set_tests_properties([=[retry_mechanics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1047;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[monotonic_deadline_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-monotonic-deadline-test")
set_tests_properties([=[monotonic_deadline_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1055;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[privilege_escalation_adversarial_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-privilege-escalation-adversarial-test")
set_tests_properties([=[privilege_escalation_adversarial_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1347;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[execution_storm_backpressure_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-execution-storm-backpressure-test")
set_tests_properties([=[execution_storm_backpressure_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1355;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cancellation_race_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cancellation-race-test")
set_tests_properties([=[cancellation_race_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1369;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[read_file_operation_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-read-file-operation-test")
set_tests_properties([=[read_file_operation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1377;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[mutation_integration_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-mutation-integration-test")
set_tests_properties([=[mutation_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1386;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[read_only_command_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-read-only-command-test")
set_tests_properties([=[read_only_command_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1416;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[timeout_ambiguity_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-timeout-ambiguity-test")
set_tests_properties([=[timeout_ambiguity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1424;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
