# CMake generated Testfile for 
# Source directory: /home/bvrznski/rebuntu/cpp
# Build directory: /home/bvrznski/rebuntu/cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[context_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-context-test")
set_tests_properties([=[context_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;117;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[exec_diag_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-exec-diag-test")
set_tests_properties([=[exec_diag_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;470;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_link_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-link-test")
set_tests_properties([=[netlink_link_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;549;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_route_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-route-test")
set_tests_properties([=[netlink_route_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;564;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_socket_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-socket-test")
set_tests_properties([=[netlink_socket_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;579;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[drm_topology_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-drm-topology-test")
set_tests_properties([=[drm_topology_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;594;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[procfs_process_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-procfs-process-test")
set_tests_properties([=[procfs_process_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;609;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[isolated_provider_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-isolated-provider-test")
set_tests_properties([=[isolated_provider_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;616;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[provider_evidence_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-provider-evidence-test")
set_tests_properties([=[provider_evidence_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;624;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[command_model_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-command-model-test")
set_tests_properties([=[command_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;631;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[collision_scanner_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-collision-scanner-test")
set_tests_properties([=[collision_scanner_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;639;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[predicates_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-predicates-test")
set_tests_properties([=[predicates_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;647;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[scope_grammar_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-scope-grammar-test")
set_tests_properties([=[scope_grammar_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;655;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[pipeline_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-pipeline-test")
set_tests_properties([=[pipeline_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;663;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[value_parsers_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-value-parsers-test")
set_tests_properties([=[value_parsers_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;671;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[systemd_service_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-systemd-service-test")
set_tests_properties([=[systemd_service_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;726;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[procfs_modules_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-procfs-modules-test")
set_tests_properties([=[procfs_modules_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;733;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cgroup_hierarchy_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cgroup-hierarchy-test")
set_tests_properties([=[cgroup_hierarchy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;741;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[evidence_deduplication_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-evidence-deduplication-test")
set_tests_properties([=[evidence_deduplication_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;850;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[hang_stall_jam_detector_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-hang-stall-jam-detector-test")
set_tests_properties([=[hang_stall_jam_detector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;874;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[parallel_discovery_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-parallel-discovery-test")
set_tests_properties([=[parallel_discovery_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;885;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[discovery_resync_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-discovery-resync-test")
set_tests_properties([=[discovery_resync_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;893;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cli_inventory_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cli-inventory-test")
set_tests_properties([=[cli_inventory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;917;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[exit_result_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-exit-result-test")
set_tests_properties([=[exit_result_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;934;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[idempotency_classifier_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-idempotency-test")
set_tests_properties([=[idempotency_classifier_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;942;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[retry_mechanics_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-retry-mechanics-test")
set_tests_properties([=[retry_mechanics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;950;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[monotonic_deadline_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-monotonic-deadline-test")
set_tests_properties([=[monotonic_deadline_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;958;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[hotplug_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-hotplug-test")
set_tests_properties([=[hotplug_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1019;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_adversarial_audit_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-adversarial-audit-test")
set_tests_properties([=[netlink_adversarial_audit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1026;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[evidence_journal_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-evidence-journal-test")
set_tests_properties([=[evidence_journal_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1041;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[provider_test_matrix]=] "/home/bvrznski/rebuntu/cpp/rebuntu-provider-test-matrix")
set_tests_properties([=[provider_test_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1048;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[privilege_helper_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-privilege-requirement-test")
set_tests_properties([=[privilege_helper_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1064;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[shell_boundary_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-shell-boundary-test")
set_tests_properties([=[shell_boundary_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1092;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[semantic_service_absence_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-semantic-service-absence-test")
set_tests_properties([=[semantic_service_absence_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1100;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[shell_output_capture_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-shell-output-capture-test")
set_tests_properties([=[shell_output_capture_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1108;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[replay_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-replay-test")
set_tests_properties([=[replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1124;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[batch_command_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-batch-command-test")
set_tests_properties([=[batch_command_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1143;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[sequential_composition_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-sequential-composition-test")
set_tests_properties([=[sequential_composition_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1160;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[parallel_composition_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-parallel-composition-test")
set_tests_properties([=[parallel_composition_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1167;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[dependency_aware_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-dependency-aware-test")
set_tests_properties([=[dependency_aware_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1179;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[stale_plan_adversarial_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-stale-plan-adversarial-test")
set_tests_properties([=[stale_plan_adversarial_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1210;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[ambiguous_target_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-ambiguous-target-test")
set_tests_properties([=[ambiguous_target_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1218;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
