# CMake generated Testfile for 
# Source directory: /home/bvrznski/rebuntu/cpp
# Build directory: /home/bvrznski/rebuntu/cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[context_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-context-test")
set_tests_properties([=[context_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;117;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[exec_diag_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-exec-diag-test")
set_tests_properties([=[exec_diag_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;456;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_link_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-link-test")
set_tests_properties([=[netlink_link_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;535;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_route_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-route-test")
set_tests_properties([=[netlink_route_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;550;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_socket_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-socket-test")
set_tests_properties([=[netlink_socket_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;565;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[drm_topology_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-drm-topology-test")
set_tests_properties([=[drm_topology_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;580;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[procfs_process_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-procfs-process-test")
set_tests_properties([=[procfs_process_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;595;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[isolated_provider_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-isolated-provider-test")
set_tests_properties([=[isolated_provider_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;602;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[command_model_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-command-model-test")
set_tests_properties([=[command_model_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;609;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[collision_scanner_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-collision-scanner-test")
set_tests_properties([=[collision_scanner_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;617;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[predicates_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-predicates-test")
set_tests_properties([=[predicates_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;625;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[scope_grammar_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-scope-grammar-test")
set_tests_properties([=[scope_grammar_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;633;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[pipeline_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-pipeline-test")
set_tests_properties([=[pipeline_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;641;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[value_parsers_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-value-parsers-test")
set_tests_properties([=[value_parsers_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;649;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[systemd_service_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-systemd-service-test")
set_tests_properties([=[systemd_service_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;704;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[procfs_modules_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-procfs-modules-test")
set_tests_properties([=[procfs_modules_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;711;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cgroup_hierarchy_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cgroup-hierarchy-test")
set_tests_properties([=[cgroup_hierarchy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;719;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[evidence_deduplication_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-evidence-deduplication-test")
set_tests_properties([=[evidence_deduplication_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;828;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[hang_stall_jam_detector_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-hang-stall-jam-detector-test")
set_tests_properties([=[hang_stall_jam_detector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;852;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[parallel_discovery_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-parallel-discovery-test")
set_tests_properties([=[parallel_discovery_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;863;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[discovery_resync_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-discovery-resync-test")
set_tests_properties([=[discovery_resync_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;871;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[cli_inventory_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-cli-inventory-test")
set_tests_properties([=[cli_inventory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;895;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[exit_result_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-exit-result-test")
set_tests_properties([=[exit_result_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;910;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[idempotency_classifier_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-idempotency-test")
set_tests_properties([=[idempotency_classifier_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;918;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[retry_mechanics_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-retry-mechanics-test")
set_tests_properties([=[retry_mechanics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;926;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[monotonic_deadline_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-monotonic-deadline-test")
set_tests_properties([=[monotonic_deadline_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;934;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[hotplug_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-hotplug-test")
set_tests_properties([=[hotplug_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;995;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[netlink_adversarial_audit_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-netlink-adversarial-audit-test")
set_tests_properties([=[netlink_adversarial_audit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1002;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[evidence_journal_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-evidence-journal-test")
set_tests_properties([=[evidence_journal_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1017;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[provider_test_matrix]=] "/home/bvrznski/rebuntu/cpp/rebuntu-provider-test-matrix")
set_tests_properties([=[provider_test_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1024;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[privilege_helper_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-privilege-requirement-test")
set_tests_properties([=[privilege_helper_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1040;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[shell_boundary_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-shell-boundary-test")
set_tests_properties([=[shell_boundary_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1068;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[shell_output_capture_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-shell-output-capture-test")
set_tests_properties([=[shell_output_capture_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1076;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[replay_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-replay-test")
set_tests_properties([=[replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1092;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
add_test([=[batch_command_test]=] "/home/bvrznski/rebuntu/cpp/rebuntu-batch-command-test")
set_tests_properties([=[batch_command_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/bvrznski/rebuntu/cpp/CMakeLists.txt;1111;add_test;/home/bvrznski/rebuntu/cpp/CMakeLists.txt;0;")
