#include <runtime/phases_46_53.hpp>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <regex>
#include <sstream>
#include <sys/utsname.h>
#include <unistd.h>
namespace fs=std::filesystem; namespace rebuntu::platform::v4653 {
static int rv(Risk r){return static_cast<int>(r);} static bool match(const std::set<std::string>&s,const std::string&v){return s.empty()||s.count(v)||s.count("*");}
bool TaskContext::fresh()const{return Clock::now()-captured<=ttl;}
void TaskPolicyEngine::add(PolicyRule r){rules_.push_back(std::move(r));std::stable_sort(rules_.begin(),rules_.end(),[](auto&a,auto&b){return a.priority>b.priority;});}
PolicyResult TaskPolicyEngine::evaluate(const Task&t)const{for(auto&r:rules_){if(!match(r.origins,t.origin)||!match(r.verbs,t.verb)||!match(r.targets,t.target)||rv(t.risk)>rv(r.max_risk))continue;if(r.require_local&&!t.requester.local)continue;if(r.require_fresh_context&&!t.context.fresh())return{Decision::clarify,r.id,"context is stale",{"fresh_context"}};if(r.require_reversible&&!t.reversible)return{Decision::deny,r.id,"operation is not reversible",{}};bool role=r.roles.empty();for(auto&x:t.requester.roles)role|=r.roles.count(x);if(!role)continue;std::vector<std::string>missing;for(auto&k:r.required_context)if(!t.context.facts.count(k))missing.push_back(k);for(auto&c:t.required_capabilities)if(!t.requester.capabilities.count(c))missing.push_back("capability:"+c);if(!missing.empty())return{Decision::clarify,r.id,"required context or capability missing",missing};return{r.decision,r.id,"matched deterministic policy",{}};}return{Decision::deny,"default-deny","no policy rule authorized the task",{}};}
void ContextEngine::source(std::string n,Source s){if(!n.empty()&&s)sources_[std::move(n)]=std::move(s);}TaskContext ContextEngine::capture(std::string cwd,std::string session,std::string host,const std::set<std::string>&keys)const{TaskContext c;c.cwd=std::move(cwd);c.session=std::move(session);c.host=std::move(host);for(auto&k:keys)for(auto&[n,s]:sources_)if(auto v=s(k)){auto key=n+":"+k;c.facts[key]=v->first;c.provenance.push_back(v->second);}return c;}std::vector<std::string> ContextEngine::conflicts(const TaskContext&c)const{std::map<std::string,std::set<std::string>>v;for(auto&[k,x]:c.facts){auto p=k.find(':');v[p==std::string::npos?k:k.substr(p+1)].insert(x);}std::vector<std::string>r;for(auto&[k,x]:v)if(x.size()>1)r.push_back(k);return r;}
NaturalLanguageOperator::NaturalLanguageOperator(v4045::UnifiedControlPlane&c):control_(c){}void NaturalLanguageOperator::semantic_provider(SemanticProvider s){semantic_=std::move(s);}void NaturalLanguageOperator::policy(TaskPolicyEngine*p){policy_=p;}
NaturalLanguageOperator::Reply NaturalLanguageOperator::ask(const std::string&text,const Principal&p,const TaskContext&ctx,bool approved){if(text.empty())return{Decision::clarify,"empty request"};if(!semantic_)return{Decision::defer,"semantic provider unavailable"};auto cs=semantic_(text,ctx);if(cs.empty())return{Decision::clarify,"request could not be resolved"};std::stable_sort(cs.begin(),cs.end(),[](auto&a,auto&b){return a.confidence>b.confidence;});auto c=cs.front();if(c.confidence<.55||!c.ambiguities.empty())return{Decision::clarify,"request is ambiguous",{}, {}, c.ambiguities};Task t{"task-"+std::to_string(++seq_),"ask",c.verb,c.target,p,ctx,c.arguments,c.destructive?Risk::critical:c.privileged?Risk::high:c.mutating?Risk::medium:Risk::low,c.mutating,c.privileged,c.destructive,!c.destructive};t.required_capabilities.insert("task:"+c.verb);PolicyResult pr=policy_?policy_->evaluate(t):PolicyResult{Decision::deny,"no-policy","policy engine unavailable",{}};if(pr.decision!=Decision::allow)return{pr.decision,pr.reason,t,{},pr.missing};auto op=control_.plan("semantic",c.verb,c.target,c.arguments,c.mutating,c.privileged,c.destructive);if(!control_.validate(op))return{Decision::deny,"control-plane validation failed",t,op};if(!control_.authorize(op,approved||(!c.mutating&&!c.privileged&&!c.destructive)))return{Decision::justify,"operator approval required",t,op};if(!control_.execute(op)||!control_.verify(op))return{Decision::deny,"execution or verification failed",t,op};return{Decision::allow,"verified",t,op};}
GuiBoundary::GuiBoundary(NaturalLanguageOperator&a):ask_(a){}NaturalLanguageOperator::Reply GuiBoundary::submit(const GuiRequest&r,bool approved){std::ostringstream q;q<<r.action<<" "<<r.target;return ask_.ask(q.str(),r.principal,r.context,approved);}std::vector<std::string>GuiBoundary::surfaces()const{return{"overview","search","tasks","workflows","system","security","history"};}
PlatformInfo LinuxAdapter::inspect()const{struct utsname u{};::uname(&u);char h[256]{};::gethostname(h,sizeof(h)-1);PlatformInfo p{"linux",u.release,u.machine,h,{}};p.capabilities["procfs"]=fs::exists("/proc")?"true":"false";p.capabilities["sysfs"]=fs::exists("/sys")?"true":"false";p.capabilities["systemd"]=fs::exists("/run/systemd/system")?"true":"false";return p;}bool LinuxAdapter::supports(const std::string&x)const{return x=="procfs"?fs::exists("/proc"):x=="sysfs"?fs::exists("/sys"):x=="systemd"?fs::exists("/run/systemd/system"):false;}std::optional<std::string>LinuxAdapter::read(const std::string&p)const{if(p.empty()||p[0]!='/'||(p.rfind("/proc/",0)!=0&&p.rfind("/sys/",0)!=0))return{};std::ifstream f(p);if(!f)return{};std::string s;std::getline(f,s);return s;}
bool Fabric::admit(Node n){if(n.id.empty()||n.endpoint.empty())return false;return nodes_.emplace(n.id,std::move(n)).second;}bool Fabric::remove(const std::string&id){return nodes_.erase(id)>0;}bool Fabric::quarantine(const std::string&id,bool q){auto i=nodes_.find(id);if(i==nodes_.end())return false;i->second.quarantined=q;return true;}std::vector<Node>Fabric::members()const{std::vector<Node>r;for(auto&[_,n]:nodes_)r.push_back(n);return r;}std::optional<Node>Fabric::choose(const std::set<std::string>&caps)const{for(auto&[_,n]:nodes_){if(n.quarantined||n.draining)continue;bool ok=true;for(auto&c:caps)ok&=n.capabilities.count(c);if(ok)return n;}return{};}RemoteResult Fabric::dispatch(const Task&t,const std::string&id,const std::function<RemoteResult(const Task&,const Node&)>&fn)const{auto i=nodes_.find(id);if(i==nodes_.end()||i->second.quarantined||i->second.draining)return{false,false,false,"target unavailable"};for(auto&c:t.required_capabilities)if(!i->second.capabilities.count(c))return{false,false,false,"target lacks capability"};try{return fn(t,i->second);}catch(...){return{true,false,true,"remote outcome indeterminate"};}}
bool AssociationManager::local(SystemIdentity x){if(x.id.empty()||x.fingerprint.empty()||x.public_material.empty()||x.revoked)return false;local_=std::move(x);return true;}bool AssociationManager::associate(SystemIdentity p,std::string proof){if(!local_||p.id.empty()||p.revoked||proof.empty()||p.id==local_->id)return false;peers_[p.id]=std::move(p);return true;}std::optional<AssociationGrant>AssociationManager::grant(const std::string&peer,std::set<std::string>caps,std::chrono::seconds ttl){if(!peers_.count(peer)||ttl<=std::chrono::seconds::zero()||caps.empty())return{};AssociationGrant g{"grant-"+std::to_string(++seq_),peer,std::move(caps),Clock::now()+ttl,false};grants_[g.id]=g;return g;}bool AssociationManager::authorize(const std::string&gid,const std::string&cap)const{auto i=grants_.find(gid);return i!=grants_.end()&&!i->second.revoked&&Clock::now()<i->second.expires&&i->second.capabilities.count(cap);}bool AssociationManager::revoke(const std::string&id){auto i=grants_.find(id);if(i==grants_.end())return false;i->second.revoked=true;return true;}
bool InformationFlow::can_read(const Label&s,const Label&o){if(static_cast<int>(s.secrecy)<static_cast<int>(o.secrecy))return false;if(static_cast<int>(s.integrity)>static_cast<int>(o.integrity))return false;return std::includes(s.compartments.begin(),s.compartments.end(),o.compartments.begin(),o.compartments.end());}bool InformationFlow::can_write(const Label&s,const Label&o){if(static_cast<int>(s.secrecy)>static_cast<int>(o.secrecy))return false;if(static_cast<int>(s.integrity)<static_cast<int>(o.integrity))return false;return std::includes(o.compartments.begin(),o.compartments.end(),s.compartments.begin(),s.compartments.end());}bool InformationFlow::can_flow(const Label&f,const Label&t){return static_cast<int>(f.secrecy)<=static_cast<int>(t.secrecy)&&static_cast<int>(f.integrity)>=static_cast<int>(t.integrity)&&std::includes(t.compartments.begin(),t.compartments.end(),f.compartments.begin(),f.compartments.end());}
PhaseCoverage::PhaseCoverage(std::string root){for(int p=46;p<=53;p++){Coverage c;c.phase=p;std::error_code ec;for(auto&e:fs::directory_iterator(root,ec)){auto n=e.path().filename().string();if(e.is_directory()&&n.rfind("phase-"+std::to_string(p)+"-",0)==0){auto d=e.path();c.architecture_present=fs::exists(d/"architecture",ec);if(fs::exists(d/"manifest.json",ec)){std::ifstream f(d/"manifest.json");std::string s((std::istreambuf_iterator<char>(f)),{});std::smatch m;if(std::regex_search(s,m,std::regex("\"(?:full_prompt_count|prompt_count)\"\\s*:\s*(\\d+)")))c.prompt_count=std::stoull(m[1]);if(std::regex_search(s,m,std::regex("\"name\"\\s*:\s*\"([^\"]+)")))c.manifest_name=m[1];}if(!c.prompt_count){for(auto&x:fs::recursive_directory_iterator(d,ec))if(x.is_regular_file()&&x.path().extension()==".md"&&std::regex_match(x.path().filename().string(),std::regex(std::to_string(p)+R"(\.\d+.*\.md)")))c.prompt_count++;}c.implemented=true;break;}}rows_.push_back(c);}}bool PhaseCoverage::complete()const{return rows_.size()==8&&std::all_of(rows_.begin(),rows_.end(),[](auto&x){return x.prompt_count>0&&x.implemented;});}
}
