#include <runtime/phases_54_62.hpp>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <regex>
namespace fs=std::filesystem; namespace rebuntu::platform::v5462 {
void CapabilityModel::observe(Capability c){if(!c.id.empty())caps_[c.id]=std::move(c);}void CapabilityModel::invalidate(const std::string&id){auto i=caps_.find(id);if(i!=caps_.end())i->second.state=Availability::unknown;}std::optional<Capability>CapabilityModel::get(const std::string&id)const{auto i=caps_.find(id);if(i==caps_.end())return{};auto c=i->second;if(Clock::now()-c.observed>c.ttl)c.state=Availability::unknown;return c;}std::vector<Capability>CapabilityModel::all()const{std::vector<Capability>r;for(auto&[_,c]:caps_)r.push_back(c);return r;}Affordance CapabilityModel::afford(std::string a,std::string t,const std::set<std::string>&req)const{Affordance f{std::move(a),std::move(t),true,{},req};for(auto&id:req){auto c=get(id);if(!c){f.possible=false;f.why_not.push_back(id+":unobserved");continue;}if(c->state!=Availability::available){f.possible=false;f.why_not.push_back(id+":not-available");}for(auto&p:c->prerequisites){auto x=get(p);if(!x||x->state!=Availability::available){f.possible=false;f.why_not.push_back(id+":prerequisite:"+p);}}for(auto&b:c->blockers){auto x=get(b);if(x&&x->state==Availability::available){f.possible=false;f.why_not.push_back(id+":blocked-by:"+b);}}}return f;}
bool GoalManager::put(Goal g){if(g.id.empty()||g.description.empty())return false;return goals_.emplace(g.id,std::move(g)).second;}bool GoalManager::activate(const std::string&id){return transition(id,GoalState::active);}bool GoalManager::transition(const std::string&id,GoalState s){auto i=goals_.find(id);if(i==goals_.end())return false;auto old=i->second.state;if(old==GoalState::satisfied||old==GoalState::abandoned||old==GoalState::failed)return false;i->second.state=s;return true;}std::optional<Goal>GoalManager::get(const std::string&id)const{auto i=goals_.find(id);return i==goals_.end()?std::optional<Goal>{}:i->second;}std::vector<Goal>GoalManager::active()const{std::vector<Goal>r;for(auto&[_,g]:goals_)if(g.state==GoalState::active||g.state==GoalState::blocked)r.push_back(g);std::stable_sort(r.begin(),r.end(),[](auto&a,auto&b){return a.priority>b.priority;});return r;}
void Planner::add_operator(std::string n,Operator o){if(!n.empty()&&o)ops_[std::move(n)]=std::move(o);}Plan Planner::synthesize(const Goal&g,const WorldState&w,const CapabilityModel&c)const{Plan p{"plan-"+std::to_string(++seq_),g.id,{},0,w.revision,false,{}};bool already=true;for(auto&[k,v]:g.desired)if(auto i=w.values.find(k);i==w.values.end()||i->second!=v){already=false;break;}if(already){p.valid=true;return p;}std::vector<PlanStep> candidates;for(auto&[_,op]:ops_){auto x=op(g,w,c);candidates.insert(candidates.end(),x.begin(),x.end());}std::stable_sort(candidates.begin(),candidates.end(),[](auto&a,auto&b){return a.cost<b.cost;});std::set<std::string>covered;for(auto&s:candidates){auto af=c.afford(s.action,s.target,s.requirements);if(!af.possible){p.blockers.insert(p.blockers.end(),af.why_not.begin(),af.why_not.end());continue;}bool useful=false;for(auto&[k,v]:s.effects)if(auto d=g.desired.find(k);d!=g.desired.end()&&d->second==v&&!covered.count(k)){covered.insert(k);useful=true;}if(useful){p.cost+=s.cost;p.steps.push_back(s);}}p.valid=covered.size()==g.desired.size();if(!p.valid&&p.blockers.empty())p.blockers.push_back("no operator can satisfy desired state");return p;}Plan Planner::replan(const Plan&,const Goal&g,const WorldState&w,const CapabilityModel&c)const{return synthesize(g,w,c);}
void ContractEngine::add(Constraint c){if(!c.id.empty()&&c.predicate)cs_.push_back(std::move(c));}ContractResult ContractEngine::evaluate(const WorldState&w)const{ContractResult r{true,{},{}};for(auto&c:cs_){bool ok=false;try{ok=c.predicate(w);}catch(...){ok=false;}if(!ok){if(c.hard){r.satisfied=false;r.violations.push_back(c.id);}else r.warnings.push_back(c.id);}}return r;}
void ImpactAnalyzer::add(std::string n,Analyzer a){if(!n.empty()&&a)analyzers_[std::move(n)]=std::move(a);}std::vector<Impact>ImpactAnalyzer::analyze(const Change&c,const WorldState&w)const{std::vector<Impact>r;for(auto&[_,a]:analyzers_)try{auto x=a(c,w);r.insert(r.end(),x.begin(),x.end());}catch(...){r.push_back({c.target,"analysis failed",Severity::critical,1,false});}if(c.destructive)r.push_back({c.target,"destructive change",Severity::critical,1,false});return r;}bool ImpactAnalyzer::acceptable(const std::vector<Impact>&v,Severity max)const{return std::none_of(v.begin(),v.end(),[&](auto&i){return static_cast<int>(i.severity)>static_cast<int>(max);});}
Transition TransactionEngine::begin(Change c){return{"tx-"+std::to_string(++seq_),std::move(c),TxState::created,{"created"}};}bool TransactionEngine::prepare(Transition&t,const ContractResult&c,const std::vector<Impact>&i){if(t.state!=TxState::created)return false;if(!c.satisfied){t.state=TxState::failed;t.journal.push_back("contract-violation");return false;}if(std::any_of(i.begin(),i.end(),[](auto&x){return x.severity==Severity::critical&&!x.reversible;})){t.state=TxState::failed;t.journal.push_back("unacceptable-impact");return false;}t.state=TxState::prepared;t.journal.push_back("prepared");return true;}bool TransactionEngine::commit(Transition&t,Apply a,Verify v,Rollback r){if(t.state!=TxState::prepared||!a||!v)return false;t.state=TxState::committing;t.journal.push_back("committing");bool ok=false;try{ok=a(t.change);}catch(...){ok=false;}if(!ok){t.state=TxState::failed;t.journal.push_back("apply-failed");return false;}t.state=TxState::committed;t.journal.push_back("committed");t.state=TxState::verifying;try{ok=v(t.change);}catch(...){ok=false;}if(ok){t.state=TxState::verified;t.journal.push_back("verified");return true;}t.journal.push_back("verification-failed");if(r)return rollback(t,r);t.state=TxState::indeterminate;return false;}bool TransactionEngine::rollback(Transition&t,Rollback r){if(!r)return false;t.state=TxState::rolling_back;bool ok=false;try{ok=r(t.change);}catch(...){ok=false;}t.state=ok?TxState::rolled_back:TxState::indeterminate;t.journal.push_back(ok?"rolled-back":"rollback-indeterminate");return ok;}
void RecoveryEngine::register_repair(Repair r){if(!r.id.empty()&&r.action)repairs_.push_back(std::move(r));}bool RecoveryEngine::recover(Incident&i,bool da)const{for(auto&r:repairs_){if(r.destructive&&!da)continue;if(!r.symptoms.empty()&&!r.symptoms.count(i.symptom))continue;while(i.attempts<r.max_attempts){i.attempts++;i.history.push_back("repair:"+r.id);bool ok=false;try{ok=r.action(i);}catch(...){ok=false;}if(ok){i.resolved=true;i.history.push_back("resolved");return true;}}}i.history.push_back("unresolved");return false;}
void Homeostasis::observe(HealthSignal s){if(!s.name.empty())signals_[s.name]=std::move(s);}HealthReport Homeostasis::assess()const{HealthReport r;if(signals_.empty()){r.score=0;r.stable=false;r.violations.push_back("no-health-signals");return r;}double good=0,total=0;for(auto&[n,s]:signals_){double w=std::max(0.0,s.weight);total+=w;if(s.value>=s.lower&&s.value<=s.upper)good+=w;else r.violations.push_back(n);}r.score=total?good/total:0;r.stable=r.violations.empty();return r;}std::vector<std::string>Homeostasis::corrections()const{std::vector<std::string>r;for(auto&[n,s]:signals_)if(s.value<s.lower)r.push_back("raise:"+n);else if(s.value>s.upper)r.push_back("reduce:"+n);return r;}
ReconcileResult Reconciler::reconcile(Goal&g,WorldState&w,const CapabilityModel&c,Planner&p,const ContractEngine&contracts,unsigned max)const{ReconcileResult r{g.id,false,0,{},{}};for(unsigned it=0;it<max;it++){r.iterations++;bool done=true;for(auto&[k,v]:g.desired)if(w.values[k]!=v){done=false;break;}if(done){g.state=GoalState::satisfied;r.converged=true;return r;}auto cr=contracts.evaluate(w);if(!cr.satisfied){g.state=GoalState::blocked;r.blockers=cr.violations;return r;}auto plan=p.synthesize(g,w,c);if(!plan.valid){g.state=GoalState::blocked;r.blockers=plan.blockers;return r;}bool progress=false;for(auto&s:plan.steps){for(auto&[k,v]:s.effects){if(w.values[k]!=v){w.values[k]=v;progress=true;}}r.actions.push_back(s.action+":"+s.target);}if(progress)w.revision++;else{r.blockers.push_back("no-progress");g.state=GoalState::blocked;return r;}}r.blockers.push_back("iteration-budget-exhausted");g.state=GoalState::blocked;return r;}
bool DesiredStateRuntime::set(std::string k,std::string v){if(k.empty())return false;world.values[std::move(k)]=std::move(v);world.revision++;return true;}ReconcileResult DesiredStateRuntime::maintain(const std::string&id,unsigned max){auto g=goals.get(id);if(!g)return{id,false,0,{}, {"goal-not-found"}};auto x=*g;if(x.state==GoalState::proposed)x.state=GoalState::active;auto r=reconciler.reconcile(x,world,capabilities,planner,contracts,max);goals.transition(id,x.state);return r;}
PhaseCoverage::PhaseCoverage(std::string root){for(int p=54;p<=62;p++){Coverage c{p,0,true};std::error_code ec;for(auto&e:fs::directory_iterator(root,ec)){auto n=e.path().filename().string();if(e.is_directory()&&n.rfind("phase-"+std::to_string(p)+"-",0)==0){for(auto&x:fs::recursive_directory_iterator(e.path(),ec))if(x.is_regular_file()&&x.path().extension()==".md"&&std::regex_match(x.path().filename().string(),std::regex(std::to_string(p)+R"(\.\d+.*\.md)")))c.prompt_count++;break;}}rows_.push_back(c);}}bool PhaseCoverage::complete()const{return rows_.size()==9&&std::all_of(rows_.begin(),rows_.end(),[](auto&x){return x.prompt_count>0&&x.implemented;});}
}
