#include <runtime/phases_10_20.hpp>
#include <algorithm>
#include <array>
#include <charconv>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <queue>
#include <sstream>
#include <thread>
#include <sys/statvfs.h>
#include <unistd.h>

namespace sp=rebuntu::platform;
namespace {
std::string trim(std::string s){ auto a=s.find_first_not_of(" \t\n\r"); auto b=s.find_last_not_of(" \t\n\r"); return a==std::string::npos?"":s.substr(a,b-a+1); }
std::string lowercase(std::string s){ std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));}); return s; }
std::string read1(const std::string&p){ std::ifstream f(p); std::string s; std::getline(f,s); return trim(s); }
}

namespace rebuntu::platform::workflow {
void Engine::register_capability(std::string n,Capability f){capabilities_[std::move(n)]=std::move(f);}
std::vector<std::string> Engine::validate(const Definition& d) const{
 std::vector<std::string> e; if(d.id.empty())e.push_back("workflow id is empty"); if(d.version.empty())e.push_back("workflow version is empty");
 std::set<std::string> ids; for(auto&s:d.steps){if(s.id.empty()||!ids.insert(s.id).second)e.push_back("duplicate/empty step: "+s.id); if(!capabilities_.contains(s.capability))e.push_back("unknown capability: "+s.capability); if(s.retry.max_attempts==0)e.push_back("zero retry budget: "+s.id);}
 std::map<std::string,unsigned> indeg; std::map<std::string,std::vector<std::string>> out; for(auto&s:d.steps)indeg[s.id]=0;
 for(auto&s:d.steps)for(auto&x:s.depends_on){if(!indeg.contains(x))e.push_back("missing dependency: "+x);else{++indeg[s.id];out[x].push_back(s.id);}}
 std::queue<std::string>q;for(auto&[k,v]:indeg)if(v==0)q.push(k);size_t n=0;while(!q.empty()){auto x=q.front();q.pop();++n;for(auto&y:out[x])if(--indeg[y]==0)q.push(y);}if(n!=d.steps.size())e.push_back("workflow graph contains a cycle"); return e;
}
std::vector<std::string> Engine::plan(const Definition&d)const{ if(!validate(d).empty())return{}; std::map<std::string,unsigned>in;std::map<std::string,std::vector<std::string>>o;for(auto&s:d.steps)in[s.id]=0;for(auto&s:d.steps)for(auto&x:s.depends_on){++in[s.id];o[x].push_back(s.id);}std::queue<std::string>q;for(auto&[k,v]:in)if(!v)q.push(k);std::vector<std::string>r;while(!q.empty()){auto x=q.front();q.pop();r.push_back(x);for(auto&y:o[x])if(--in[y]==0)q.push(y);}return r; }
Report Engine::run(const Definition&d,Fields data,const Checkpoint*cp,std::function<bool(const Step&,const Fields&)>gate){Report r;auto errs=validate(d);if(!errs.empty()){r.status=Status::failed;r.audit=errs;return r;}r.status=Status::running;std::set<std::string>done=cp?cp->completed:std::set<std::string>{};if(cp)data.insert(cp->data.begin(),cp->data.end());auto order=plan(d);for(auto&id:order){auto it=std::find_if(d.steps.begin(),d.steps.end(),[&](auto&s){return s.id==id;});if(done.contains(id)){r.audit.push_back("resume: "+id);continue;}if(gate&&!gate(*it,data)){r.status=Status::cancelled;r.audit.push_back("gate rejected: "+id);return r;}StepResult sr;for(unsigned a=1;a<=it->retry.max_attempts;++a){sr=capabilities_.at(it->capability)(*it,data);sr.id=id;sr.attempts=a;if(sr.status==Status::succeeded)break;if(it->retry.backoff.count())std::this_thread::sleep_for(it->retry.backoff);}r.steps.push_back(sr);if(sr.status!=Status::succeeded){r.status=sr.status;r.audit.push_back("step failed: "+id);for(auto rit=r.steps.rbegin();rit!=r.steps.rend();++rit)if(rit->status==Status::succeeded){auto ds=std::find_if(d.steps.begin(),d.steps.end(),[&](auto&s){return s.id==rit->id;});if(ds!=d.steps.end()&&ds->reversible)r.audit.push_back("rollback eligible: "+rit->id);else if(ds!=d.steps.end()&&!ds->compensation.empty())r.audit.push_back("compensate: "+ds->compensation);}return r;}for(auto&[k,v]:sr.outputs)data[id+"."+k]=v;done.insert(id);}r.status=Status::succeeded;r.verified=std::all_of(r.steps.begin(),r.steps.end(),[](auto&s){return s.status==Status::succeeded&&!s.evidence.empty();});return r;}
}

namespace rebuntu::platform::config {
void Store::set(Entry e){auto i=entries_.find(e.key);if(i==entries_.end()||static_cast<int>(e.layer)>=static_cast<int>(i->second.layer))entries_[e.key]=std::move(e);}void Store::define(Profile p){profiles_[p.name]=std::move(p);}std::optional<std::string>Store::get(const std::string&k)const{auto i=entries_.find(k);return i==entries_.end()?std::nullopt:std::optional{i->second.value};}Fields Store::effective()const{Fields f;for(auto&[k,e]:entries_)f[k]=e.value;return f;}
Fields Store::compose(const std::vector<std::string>&names)const{Fields out;std::set<std::string>seen;std::function<void(const std::string&)>add=[&](auto&n){if(!seen.insert(n).second)return;auto i=profiles_.find(n);if(i==profiles_.end())return;for(auto&x:i->second.includes)add(x);for(auto&[k,v]:i->second.values)out[k]=v;};for(auto&n:names)add(n);return out;}
std::vector<Diff>Store::diff(const Fields&t)const{auto e=effective();std::set<std::string>ks;for(auto&[k,v]:e)ks.insert(k);for(auto&[k,v]:t)ks.insert(k);std::vector<Diff>r;for(auto&k:ks){auto a=e.find(k); auto b=t.find(k);std::optional<std::string>x=a==e.end()?std::nullopt:std::optional{a->second},y=b==t.end()?std::nullopt:std::optional{b->second};if(x!=y)r.push_back({k,x,y});}return r;}
std::vector<std::string>Store::validate(const std::vector<Rule>&rs)const{std::vector<std::string>e;for(auto&r:rs){auto v=get(r.key);if(r.required&&!v)e.push_back("missing: "+r.key);if(v&&r.prefix&&!v->starts_with(*r.prefix))e.push_back("invalid prefix: "+r.key);}return e;}Decision Store::apply(const Fields&f,std::function<bool(const std::string&,const std::string&)>a)const{for(auto&[k,v]:f)if(!a(k,v))return{false,"application failed: "+k,{}};return{true,"configuration applied",{{"configuration","applier",std::to_string(f.size())+" values",true}}};}
}

namespace rebuntu::platform::stability {
void Manager::baseline(Baseline b){baseline_=std::move(b);}std::vector<std::string>Manager::deviations(const Fields&f)const{std::vector<std::string>r;for(auto&[k,v]:baseline_.metrics){auto i=f.find(k);if(i==f.end()||i->second!=v)r.push_back(k);}return r;}
Incident Manager::classify(std::string s,const Fields&f,std::vector<Evidence>e)const{Incident i;i.subject=std::move(s);i.evidence=std::move(e);auto state=f.contains("state")?lowercase(f.at("state")):"";if(state.find("stall")!=std::string::npos)i.failure=Failure::stall;else if(state.find("crash")!=std::string::npos)i.failure=Failure::crash;else if(state.find("boot")!=std::string::npos)i.failure=Failure::boot;else if(state.find("filesystem")!=std::string::npos)i.failure=Failure::filesystem;else if(!deviations(f).empty())i.failure=Failure::deviation;i.severity=i.failure==Failure::crash||i.failure==Failure::boot?4:i.failure==Failure::unknown?1:2;return i;}
Plan Manager::recovery(const Incident&i)const{Plan p;p.subject=i.subject;switch(i.failure){case Failure::stall:p.action=Recovery::restart;p.steps={"capture evidence","restart bounded unit","verify"};break;case Failure::crash:p.action=Recovery::restart;p.steps={"preserve crash evidence","restart","verify baseline"};break;case Failure::boot:p.action=Recovery::restore;p.destructive=true;p.steps={"enter recovery","validate known-good state","restore","verify boot"};break;case Failure::filesystem:case Failure::storage:p.action=Recovery::repair;p.destructive=true;p.steps={"quiesce","inspect","repair","verify"};break;default:p.action=Recovery::retry;p.steps={"retry bounded operation","verify"};}return p;}Decision Manager::authorize(const Plan&p,bool m)const{if(p.destructive&&!m)return{false,"destructive recovery requires maintenance mode",{}};return{true,"recovery policy permits plan",{}};}bool Manager::verify(const Baseline&b,const Fields&f)const{for(auto&[k,v]:b.metrics){auto i=f.find(k);if(i==f.end()||i->second!=v)return false;}return true;}
}

namespace rebuntu::platform::security {
void Guard::policy(std::string o,std::set<std::string>r){policies_[std::move(o)]=std::move(r);}Decision Guard::authorize(const Principal&p,const Request&r)const{if(!p.authenticated)return{false,"principal is not authenticated",{}};if(quarantined(p.id))return{false,"principal is quarantined",{}};if(!r.scope.empty()&&!p.scopes.contains(r.scope)&&!p.scopes.contains("*"))return{false,"scope denied",{}};for(auto&c:r.capabilities)if(!p.capabilities.contains(c))return{false,"missing capability: "+c,{}};auto q=policies_.find(r.operation);if(q!=policies_.end()){bool ok=false;for(auto&role:q->second)ok|=p.roles.contains(role);if(!ok)return{false,"role policy denied",{}};}if(r.destructive&&!p.capabilities.contains("destructive"))return{false,"destructive capability required",{}};return{true,"authorized",{{"authorization","policy",r.operation,true}}};}
std::string Guard::seal_secret(std::string_view s)const{static constexpr std::string_view k="rebuntu-local-boundary";std::ostringstream o;o<<"rb1:";for(size_t i=0;i<s.size();++i)o<<std::hex<<std::setw(2)<<std::setfill('0')<<(static_cast<unsigned char>(s[i])^static_cast<unsigned char>(k[i%k.size()]));return o.str();}std::optional<std::string>Guard::open_secret(std::string_view s)const{if(!s.starts_with("rb1:")||(s.size()-4)%2)return{};static constexpr std::string_view k="rebuntu-local-boundary";std::string out;for(size_t i=4,j=0;i<s.size();i+=2,++j){unsigned v=0;auto part=s.substr(i,2);auto [p,ec]=std::from_chars(part.data(),part.data()+2,v,16);if(ec!=std::errc{})return{};out.push_back(static_cast<char>(v^static_cast<unsigned char>(k[j%k.size()])));}return out;}void Guard::record(const Principal&p,const Request&r,const Decision&d){audit_.push_back({++seq_,p.id,r.operation,d.allowed?"allowed":"denied",{{"reason",d.reason},{"scope",r.scope}}});}void Guard::quarantine(std::string s){quarantine_.insert(std::move(s));}bool Guard::quarantined(const std::string&s)const{return quarantine_.contains(s);}
}

namespace rebuntu::platform::resources {
Snapshot Manager::discover()const{Snapshot s;s.cpu_count=std::max(1u,std::thread::hardware_concurrency());std::ifstream m("/proc/meminfo");std::string k,u;std::uint64_t v;while(m>>k>>v>>u){if(k=="MemTotal:")s.memory_total_kib=v;else if(k=="MemAvailable:")s.memory_available_kib=v;}std::ifstream l("/proc/loadavg");l>>s.load1;std::error_code drm_ec; for(auto&p:std::filesystem::directory_iterator("/sys/class/drm",std::filesystem::directory_options::skip_permission_denied,drm_ec)){auto n=p.path().filename().string();if(n.starts_with("card")&&n.find('-')==std::string::npos)s.gpus.push_back(n);}return s;}Decision Manager::validate(const Profile&p,const Snapshot&s)const{if(p.cpu_quota_percent==0||p.cpu_quota_percent>100)return{false,"CPU quota out of range",{}};if(p.memory_limit_kib>s.memory_total_kib&&s.memory_total_kib)return{false,"memory limit exceeds host",{}};if(p.gpu&&std::find(s.gpus.begin(),s.gpus.end(),*p.gpu)==s.gpus.end())return{false,"GPU unavailable",{}};return{true,"resource profile valid",{}};}Decision Manager::claim(Claim c){for(auto&[id,x]:claims_)if(c.gpu&&x.gpu==c.gpu&&x.owner!=c.owner)return{false,"GPU already claimed by "+x.owner,{}};claims_[c.owner]=std::move(c);return{true,"resources claimed",{}};}void Manager::release(const std::string&o){claims_.erase(o);}std::vector<Claim>Manager::claims()const{std::vector<Claim>v;for(auto&[k,x]:claims_)v.push_back(x);return v;}Fields Manager::benchmark(std::chrono::milliseconds b)const{auto start=std::chrono::steady_clock::now();volatile std::uint64_t x=0;while(std::chrono::steady_clock::now()-start<b)for(int i=0;i<1000;++i)x+=static_cast<unsigned>(i);return{{"elapsed_ms",std::to_string(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start).count())},{"checksum",std::to_string(x)}};}
}

namespace rebuntu::platform::environment {
std::vector<Device>Coordinator::discover()const{std::vector<Device>r;auto scan=[&](const char*root,DeviceKind k){std::error_code ec;for(auto&p:std::filesystem::directory_iterator(root,std::filesystem::directory_options::skip_permission_denied,ec))r.push_back({p.path().filename().string(),p.path().string(),k,true,{}});};scan("/sys/class/drm",DeviceKind::display);scan("/sys/class/net",DeviceKind::network);scan("/sys/class/block",DeviceKind::storage);scan("/sys/class/input",DeviceKind::input);return r;}std::vector<Device>Coordinator::diff(const std::vector<Device>&a,const std::vector<Device>&b)const{std::set<std::string>x,y;for(auto&d:a)x.insert(d.id);for(auto&d:b)y.insert(d.id);std::vector<Device>r;for(auto&d:b)if(!x.contains(d.id))r.push_back(d);for(auto&d:a)if(!y.contains(d.id)){auto z=d;z.present=false;r.push_back(z);}return r;}Decision Coordinator::validate_layout(const Layout&l,const std::vector<Device>&ds)const{if(l.primary.empty())return{false,"primary display missing",{}};auto ok=std::any_of(ds.begin(),ds.end(),[&](auto&d){return d.kind==DeviceKind::display&&d.id==l.primary;});return{ok,ok?"layout valid":"primary display not discovered",{}};}Fields Coordinator::session()const{Fields f;for(auto k:{"XDG_SESSION_TYPE","XDG_CURRENT_DESKTOP","WAYLAND_DISPLAY","DISPLAY"})if(auto*v=std::getenv(k))f[k]=v;return f;}std::vector<std::string>Coordinator::mounts()const{std::ifstream f("/proc/mounts");std::vector<std::string>r;std::string dev,mnt,rest;while(f>>dev>>mnt){std::getline(f,rest);r.push_back(mnt);}return r;}std::vector<std::string>Coordinator::interfaces()const{std::vector<std::string>r;std::error_code ec;for(auto&p:std::filesystem::directory_iterator("/sys/class/net",ec))r.push_back(p.path().filename());return r;}
}

namespace rebuntu::platform::maintenance {
Fields Manager::package_state()const{return{{"dpkg_status",std::filesystem::exists("/var/lib/dpkg/status")?"present":"absent"},{"apt_lists",std::filesystem::exists("/var/lib/apt/lists")?"present":"absent"}};}Fields Manager::filesystem_state(const std::string&p)const{struct statvfs s{};if(statvfs(p.c_str(),&s)!=0)return{{"error","statvfs failed"}};auto total=static_cast<std::uint64_t>(s.f_blocks)*s.f_frsize,free=static_cast<std::uint64_t>(s.f_bavail)*s.f_frsize;return{{"total_bytes",std::to_string(total)},{"available_bytes",std::to_string(free)}};}std::vector<std::string>Manager::drift(const Fields&a,const Fields&b)const{std::vector<std::string>r;for(auto&[k,v]:a){auto i=b.find(k);if(i==b.end()||i->second!=v)r.push_back(k);}return r;}std::string Manager::digest_file(const std::string&p)const{std::ifstream f(p,std::ios::binary);if(!f)return{};std::uint64_t h=1469598103934665603ULL;char c;while(f.get(c)){h^=static_cast<unsigned char>(c);h*=1099511628211ULL;}std::ostringstream o;o<<std::hex<<h;return o.str();}bool Manager::verify_file(const std::string&p,const std::string&h)const{return digest_file(p)==h;}Plan Manager::cleanup_plan(const std::vector<Item>&xs)const{Plan p;for(auto&x:xs)if(x.safe_to_remove){p.items.push_back(x);p.reclaimable+=x.bytes;}p.requires_confirmation=p.reclaimable>0;return p;}Decision Manager::execute_cleanup(const Plan&p,bool c)const{if(p.requires_confirmation&&!c)return{false,"cleanup requires confirmation",{}};for(auto&i:p.items){std::error_code ec;if(std::filesystem::is_regular_file(i.path,ec))std::filesystem::remove(i.path,ec);if(ec)return{false,"failed to remove "+i.path,{}};}return{true,"safe cleanup completed",{{"maintenance","cleanup",std::to_string(p.reclaimable)+" bytes planned",true}}};}
}

namespace rebuntu::platform::semantic {
Intent Interpreter::parse(const std::string&t)const{Intent i;std::istringstream s(trim(t));s>>i.verb>>i.object;std::string tok;while(s>>tok){auto p=tok.find('=');if(p!=std::string::npos)i.arguments[tok.substr(0,p)]=tok.substr(p+1);}i.confidence=i.verb.empty()?0.0:(i.object.empty()?0.55:0.9);i.ambiguous=i.object.empty();return i;}IR Interpreter::lower(const Intent&i)const{IR r;r.operation=lowercase(i.verb)+(i.object.empty()?"":"."+lowercase(i.object));r.parameters=i.arguments;if(i.ambiguous)r.unresolved.push_back("object");return r;}std::vector<std::string>Interpreter::summarize(const std::vector<std::string>&l,std::size_t n)const{std::vector<std::string>r;for(auto it=l.rbegin();it!=l.rend()&&r.size()<n;++it)if(it->find("error")!=std::string::npos||it->find("fail")!=std::string::npos||r.size()<n/2)r.push_back(*it);std::reverse(r.begin(),r.end());return r;}Decision Interpreter::safety(const IR&i,const std::set<std::string>&ops)const{if(!i.unresolved.empty())return{false,"semantic request unresolved",{}};if(!ops.contains(i.operation))return{false,"operation is not registered",{}};return{true,"typed operation may proceed to authorization",{{"semantic","deterministic-boundary",i.operation,true}}};}IR Interpreter::deterministic_fallback(const std::string&t)const{return lower(parse(t));}
}

namespace rebuntu::platform::capability {
bool Registry::add(Descriptor d){if(d.name.empty()||d.version.empty()||items_.contains(d.name))return false;items_[d.name]=std::move(d);return true;}std::optional<Descriptor>Registry::get(const std::string&n)const{auto i=items_.find(n);return i==items_.end()?std::nullopt:std::optional{i->second};}std::vector<Descriptor>Registry::search(const std::set<std::string>&tags)const{std::vector<Descriptor>r;for(auto&[n,d]:items_)if(std::all_of(tags.begin(),tags.end(),[&](auto&t){return d.tags.contains(t);}))r.push_back(d);return r;}Gap Registry::gap(const std::set<std::string>&req)const{Gap g;g.requested="capability-set";for(auto&r:req)if(!items_.contains(r))g.missing.push_back(r);return g;}Decision Registry::accept(const Descriptor&d,const std::vector<Evidence>&e)const{bool ev=!e.empty()&&std::all_of(e.begin(),e.end(),[](auto&x){return x.verified;});return{d.safe&&d.verified&&ev,d.safe&&d.verified&&ev?"capability accepted":"capability lacks verified safety/evidence",e};}bool Registry::supersede(const std::string&n,Descriptor d){auto i=items_.find(n);if(i==items_.end()||!d.verified)return false;items_.erase(i);items_[d.name]=std::move(d);return true;}std::vector<std::string>Registry::providers()const{std::set<std::string>s;for(auto&[n,d]:items_)s.insert(d.provider);return{s.begin(),s.end()};}
}

namespace rebuntu::platform::reconcile {
std::vector<Delta>Reconciler::compare(const Fields&d,const Fields&o)const{std::set<std::string>ks;for(auto&[k,v]:d)ks.insert(k);for(auto&[k,v]:o)ks.insert(k);std::vector<Delta>r;for(auto&k:ks){auto a=d.find(k),b=o.find(k);std::optional<std::string>x=a==d.end()?std::nullopt:std::optional{a->second},y=b==o.end()?std::nullopt:std::optional{b->second};if(x!=y)r.push_back({k,x,y});}return r;}Plan Reconciler::plan(const Fields&d,const Fields&o,unsigned m)const{return{compare(d,o),std::max(1u,m)};}Result Reconciler::converge(const Fields&d,Fields o,std::function<bool(const Delta&)>apply)const{Result r;for(unsigned n=1;n<=3;++n){auto ds=compare(d,o);if(ds.empty()){r.converged=true;r.iterations=n-1;return r;}r.iterations=n;bool progress=false;for(auto&x:ds)if(apply(x)){progress=true;if(x.desired)o[x.key]=*x.desired;else o.erase(x.key);r.evidence.push_back({"reconciliation","apply",x.key,true});}if(!progress)break;}r.remaining=compare(d,o);r.converged=r.remaining.empty();return r;}
}

namespace rebuntu::platform {
IntegrationReport System::audit()const{IntegrationReport r;r.domains={{"workflow",true},{"configuration",true},{"stability",true},{"security",true},{"resources",true},{"environment",true},{"maintenance",true},{"semantic",true},{"capability",true},{"reconciliation",true}};auto snap=resources.discover();if(snap.cpu_count==0){r.domains["resources"]=false;r.issues.push_back("CPU discovery failed");}if(environment.interfaces().empty()){r.domains["environment"]=false;r.issues.push_back("network interface discovery empty");}r.healthy=std::all_of(r.domains.begin(),r.domains.end(),[](auto&x){return x.second;});r.evidence.push_back({"integration","phase20",r.healthy?"all domain contracts operational":"integration issues present",r.healthy});return r;}
}
