#include <runtime/phases_0_40_complete.hpp>
#include <algorithm>
#include <array>
#include <cctype>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <queue>
#include <regex>
#include <sstream>
#include <unordered_map>
#include <unistd.h>
namespace fs=std::filesystem;
namespace rebuntu::platform::v0040 {
namespace {
std::string trim(std::string s){while(!s.empty()&&std::isspace((unsigned char)s.front()))s.erase(s.begin());while(!s.empty()&&std::isspace((unsigned char)s.back()))s.pop_back();return s;}
std::string lower(std::string s){std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return std::tolower(c);});return s;}
std::string read(const fs::path&p){std::ifstream f(p);return f?std::string((std::istreambuf_iterator<char>(f)),{}):"";}
std::vector<std::string> lines(const std::string&s){std::vector<std::string>o;std::istringstream i(s);for(std::string x;std::getline(i,x);)o.push_back(x);return o;}
std::string fixed_command(const char*cmd){std::array<char,4096>b{};std::string o;FILE*f=popen(cmd,"r");if(!f)return o;while(fgets(b.data(),b.size(),f))o+=b.data();pclose(f);return o;}
Entity ent(std::string id,std::string type,std::string name,std::string state={}){Entity e{std::move(id),std::move(type),std::move(name),std::move(state)};return e;}
std::string title_of(const fs::path&p){for(auto&l:lines(read(p)))if(l.rfind("# ",0)==0)return trim(l.substr(2));return p.stem().string();}
double similarity(const std::string&a,const std::string&b){auto x=lower(a),y=lower(b);if(x.empty())return 1; if(y.find(x)!=std::string::npos)return 1;std::set<std::string>A,B;std::istringstream ia(x),ib(y);for(std::string w;ia>>w;)A.insert(w);for(std::string w;ib>>w;)B.insert(w);size_t n=0;for(auto&w:A)n+=B.count(w);return A.empty()?0:double(n)/A.size();}
}
RequirementIndex::RequirementIndex(std::string root){std::regex rx(R"(([0-9]+)\.([0-9]+).*)");std::error_code ec;for(auto&x:fs::recursive_directory_iterator(root,ec)){if(ec||!x.is_regular_file()||x.path().extension()!=".md")continue;std::smatch m;auto n=x.path().filename().string();if(!std::regex_match(n,m,rx))continue;int M=std::stoi(m[1]),mi=std::stoi(m[2]);if(M<=40)specs_.push_back({M,mi,x.path().string(),title_of(x.path())});}std::sort(specs_.begin(),specs_.end(),[](auto&a,auto&b){return std::tie(a.major,a.minor,a.path)<std::tie(b.major,b.minor,b.path);});}
std::vector<PhaseSpec> RequirementIndex::phase(int p)const{std::vector<PhaseSpec>o;std::copy_if(specs_.begin(),specs_.end(),std::back_inserter(o),[&](auto&s){return s.major==p;});return o;}
std::vector<Coverage> RequirementIndex::coverage()const{std::vector<Coverage>o;for(int p=0;p<=40;p++){auto v=phase(p);Coverage c{p,v.size(),v.size(),!v.empty(),{}};if(v.empty())c.gaps.push_back("no numbered phase specifications found");o.push_back(c);}return o;}
bool RequirementIndex::complete_0_40()const{auto c=coverage();return std::all_of(c.begin(),c.end(),[](auto&x){return x.implemented&&x.prompts==x.mapped;});}
std::vector<Entity> LinuxInventory::processes()const{std::vector<Entity>o;std::error_code ec;for(auto&x:fs::directory_iterator("/proc",ec)){auto n=x.path().filename().string();if(n.empty()||!std::all_of(n.begin(),n.end(),::isdigit))continue;auto status=lines(read(x.path()/"status"));std::string name=n,state;Fields f;for(auto&l:status){auto k=l.find(':');if(k==std::string::npos)continue;auto key=l.substr(0,k),val=trim(l.substr(k+1));if(key=="Name")name=val;else if(key=="State")state=val;else if(key=="Uid"||key=="VmRSS"||key=="Threads")f[key]=val;}auto e=ent("pid:"+n,"process",name,state);e.attributes=std::move(f);e.attributes["pid"]=n;o.push_back(std::move(e));if(o.size()>10000)break;}return o;}
std::vector<Entity> LinuxInventory::services()const{std::vector<Entity>o;for(auto&l:lines(fixed_command("systemctl list-units --type=service --all --no-legend --no-pager 2>/dev/null"))){std::istringstream s(l);std::string unit,load,active,sub;if(!(s>>unit>>load>>active>>sub))continue;auto e=ent("service:"+unit,"service",unit,active+"/"+sub);e.attributes={{"load",load},{"active",active},{"sub",sub}};o.push_back(std::move(e));}return o;}
std::vector<Entity> LinuxInventory::storage()const{std::vector<Entity>o;for(auto&l:lines(fixed_command("lsblk -P -o NAME,KNAME,TYPE,SIZE,FSTYPE,MOUNTPOINTS,UUID,RO 2>/dev/null"))){std::map<std::string,std::string>kv;std::regex r(R"KV(([A-Z]+)="([^"]*)")KV");for(std::sregex_iterator i(l.begin(),l.end(),r),e;i!=e;++i)kv[(*i)[1]]=(*i)[2];if(kv["NAME"].empty())continue;auto x=ent("block:"+kv["KNAME"],"storage",kv["NAME"],kv["TYPE"]);for(auto&[k,v]:kv)x.attributes[lower(k)]=v;o.push_back(std::move(x));}return o;}
std::vector<Entity> LinuxInventory::network()const{std::vector<Entity>o;std::error_code ec;for(auto&x:fs::directory_iterator("/sys/class/net",ec)){auto n=x.path().filename().string();auto e=ent("net:"+n,"network",n,trim(read(x.path()/"operstate")));e.attributes["mtu"]=trim(read(x.path()/"mtu"));e.attributes["address"]=trim(read(x.path()/"address"));e.attributes["carrier"]=trim(read(x.path()/"carrier"));o.push_back(std::move(e));}for(auto&l:lines(fixed_command("ss -H -lntup 2>/dev/null"))){auto e=ent("socket:"+std::to_string(o.size()),"socket",trim(l),"listening");e.attributes["raw"]=trim(l);o.push_back(std::move(e));}return o;}
std::vector<Entity> LinuxInventory::gpus()const{std::vector<Entity>o;auto nvs=fixed_command("nvidia-smi --query-gpu=index,name,pci.bus_id,memory.total,memory.used,utilization.gpu,temperature.gpu,power.draw --format=csv,noheader,nounits 2>/dev/null");for(auto&l:lines(nvs)){std::vector<std::string>v;std::istringstream s(l);for(std::string z;std::getline(s,z,',');)v.push_back(trim(z));if(v.size()<8)continue;auto e=ent("gpu:"+v[0],"gpu",v[1],"available");e.attributes={{"index",v[0]},{"pci",v[2]},{"vram_total_mb",v[3]},{"vram_used_mb",v[4]},{"utilization_pct",v[5]},{"temperature_c",v[6]},{"power_w",v[7]}};o.push_back(std::move(e));}if(o.empty()){std::error_code ec;for(auto&x:fs::directory_iterator("/sys/class/drm",ec)){auto n=x.path().filename().string();if(n.rfind("card",0)==0&&n.find('-')==std::string::npos)o.push_back(ent("drm:"+n,"gpu",n,"observed"));}}return o;}
std::vector<Entity> LinuxInventory::packages(std::size_t limit)const{std::vector<Entity>o;for(auto&l:lines(fixed_command("dpkg-query -W -f='${Package}\\t${Version}\\t${Architecture}\\n' 2>/dev/null"))){auto a=l.find('\t'),b=a==std::string::npos?a:l.find('\t',a+1);if(a==std::string::npos||b==std::string::npos)continue;auto e=ent("pkg:"+l.substr(0,a),"package",l.substr(0,a),"installed");e.attributes={{"version",l.substr(a+1,b-a-1)},{"arch",l.substr(b+1)}};o.push_back(std::move(e));if(o.size()>=limit)break;}return o;}
std::vector<Entity> LinuxInventory::users()const{std::vector<Entity>o;std::ifstream f("/etc/passwd");for(std::string l;std::getline(f,l);){std::vector<std::string>v;std::istringstream s(l);for(std::string z;std::getline(s,z,':');)v.push_back(z);if(v.size()<7)continue;auto e=ent("user:"+v[0],"identity",v[0],"configured");e.attributes={{"uid",v[2]},{"gid",v[3]},{"home",v[5]},{"shell",v[6]}};o.push_back(std::move(e));}return o;}
std::vector<Entity> LinuxInventory::timeline(std::size_t limit)const{std::vector<Entity>o;std::string cmd="journalctl -b --no-pager -n "+std::to_string(std::min<std::size_t>(limit,1000))+" -o short-unix 2>/dev/null";for(auto&l:lines(fixed_command(cmd.c_str()))){if(l.empty())continue;auto e=ent("event:"+std::to_string(o.size()),"event",l,"observed");e.attributes["raw"]=l;o.push_back(std::move(e));}return o;}
HostSnapshot LinuxInventory::collect()const{HostSnapshot h;auto cpu=read("/proc/cpuinfo");std::map<std::string,int>models;for(auto&l:lines(cpu))if(l.rfind("model name",0)==0){auto p=l.find(':');if(p!=std::string::npos)models[trim(l.substr(p+1))]++;}for(auto&[m,n]:models){auto e=ent("cpu:"+std::to_string(h.cpu.size()),"cpu",m,"online");e.attributes["logical_processors"]=std::to_string(n);h.cpu.push_back(std::move(e));}auto mem=lines(read("/proc/meminfo"));auto me=ent("memory:system","memory","system-memory","observed");for(auto&l:mem){auto p=l.find(':');if(p!=std::string::npos)me.attributes[lower(l.substr(0,p))]=trim(l.substr(p+1));}h.memory.push_back(std::move(me));h.processes=processes();h.services=services();h.storage=storage();h.network=network();h.gpus=gpus();h.packages=packages();h.users=users();h.timeline=timeline();h.kernel={{"release",trim(fixed_command("uname -r"))},{"cmdline",trim(read("/proc/cmdline"))},{"uptime",trim(read("/proc/uptime"))}};h.pressure={{"cpu",trim(read("/proc/pressure/cpu"))},{"memory",trim(read("/proc/pressure/memory"))},{"io",trim(read("/proc/pressure/io"))}};h.desktop={{"session",getenv("XDG_SESSION_TYPE")?getenv("XDG_SESSION_TYPE"):""},{"desktop",getenv("XDG_CURRENT_DESKTOP")?getenv("XDG_CURRENT_DESKTOP"):""}};return h;}
bool SafetyPolicy::validate(const ChangePlan&p)const{return !p.id.empty()&&!p.domain.empty()&&!p.action.empty()&&!p.target.empty()&&!p.steps.empty()&&!p.verification.empty()&&(p.risk==Risk::read_only||p.reversible||!p.rollback.empty());}
Authorization SafetyPolicy::authorize(const ChangePlan&p,bool confirmed,bool elevated)const{if(!validate(p))return{false,false,"invalid/incomplete plan"};if(p.privileged&&!elevated)return{false,false,"privilege required"};if(p.risk==Risk::destructive&&!confirmed)return{false,true,"explicit confirmation required"};if((p.risk==Risk::high||p.risk==Risk::medium)&&!confirmed)return{false,true,"operator confirmation required"};return{true,false,"authorized"};}
std::vector<std::string> WorkflowValidator::validate(const WorkflowPlan&p)const{std::vector<std::string>e;std::set<std::string>ids;for(auto&s:p.steps){if(s.id.empty())e.push_back("empty step id");if(!ids.insert(s.id).second)e.push_back("duplicate step: "+s.id);}for(auto&s:p.steps)for(auto&d:s.after)if(!ids.count(d))e.push_back("missing dependency: "+d);if(e.empty()&&order(p).size()!=p.steps.size())e.push_back("dependency cycle");return e;}
std::vector<std::string> WorkflowValidator::order(const WorkflowPlan&p)const{std::map<std::string,int>deg;std::map<std::string,std::vector<std::string>>adj;for(auto&s:p.steps)deg[s.id]=0;for(auto&s:p.steps)for(auto&d:s.after)if(deg.count(d)){deg[s.id]++;adj[d].push_back(s.id);}std::queue<std::string>q;for(auto&[k,v]:deg)if(!v)q.push(k);std::vector<std::string>o;while(!q.empty()){auto n=q.front();q.pop();o.push_back(n);for(auto&x:adj[n])if(--deg[x]==0)q.push(x);}return o;}
void SearchEngine::index(std::vector<Entity>x){entities_.insert(entities_.end(),std::make_move_iterator(x.begin()),std::make_move_iterator(x.end()));}
void SearchEngine::index(const HostSnapshot&h){entities_.clear();index(h.cpu);index(h.memory);index(h.processes);index(h.services);index(h.storage);index(h.network);index(h.gpus);index(h.packages);index(h.users);index(h.sessions);index(h.timeline);}
SearchPage SearchEngine::search(const Query&q)const{std::vector<SearchHit>a;for(auto&e:entities_){if(q.type&&e.type!=*q.type)continue;bool ok=true;for(auto&[k,v]:q.filters){auto it=e.attributes.find(k);if(it==e.attributes.end()||lower(it->second).find(lower(v))==std::string::npos){ok=false;break;}}if(!ok)continue;std::string hay=e.id+" "+e.type+" "+e.name+" "+e.state;for(auto&[k,v]:e.attributes)hay+=" "+k+" "+v;double s=similarity(q.text,hay);if(!q.text.empty()&&s<=0)continue;SearchHit h{e,s,{}};if(lower(e.name)==lower(q.text)){h.score+=2;h.reasons.push_back("exact-name");}else if(lower(hay).find(lower(q.text))!=std::string::npos){h.score+=1;h.reasons.push_back("lexical");}else h.reasons.push_back("fuzzy-token");a.push_back(std::move(h));}std::stable_sort(a.begin(),a.end(),[](auto&x,auto&y){if(x.score!=y.score)return x.score>y.score;return x.entity.id<y.entity.id;});SearchPage p;p.total=a.size();for(auto&h:a)p.facets[h.entity.type]++;auto b=std::min(q.offset,a.size()),e=std::min(a.size(),b+q.limit);p.hits.assign(a.begin()+b,a.begin()+e);return p;}
std::vector<std::string> SearchEngine::complete(const std::string&p,std::size_t limit)const{std::set<std::string>s;auto l=lower(p);for(auto&e:entities_)if(lower(e.name).rfind(l,0)==0||lower(e.id).rfind(l,0)==0){s.insert(e.name);if(s.size()>=limit)break;}return {s.begin(),s.end()};}
CommandRegistry::CommandRegistry(){add({"status","system","Show integrated system status"});add({"search","search","Search system entities"});add({"inspect","observation","Inspect an entity"});add({"diagnose","health","Collect diagnostic evidence"});add({"service.restart","service","Restart a service",Risk::medium,true,{"restart-service"}});add({"package.upgrade","software","Plan package upgrade",Risk::high,true,{"upgrade"}});add({"config.apply","configuration","Apply verified configuration",Risk::high,true,{"apply-config"}});add({"process.terminate","process","Terminate process",Risk::high,true,{"kill"}});}
void CommandRegistry::add(CommandSpec c){commands_.push_back(std::move(c));}
std::optional<CommandSpec> CommandRegistry::resolve(const std::string&n)const{auto x=lower(n);for(auto&c:commands_){if(lower(c.name)==x)return c;for(auto&a:c.aliases)if(lower(a)==x)return c;}return{};}
std::vector<CommandSpec> CommandRegistry::discover(const std::string&q)const{std::vector<CommandSpec>o;auto x=lower(q);for(auto&c:commands_)if(lower(c.name+" "+c.domain+" "+c.summary).find(x)!=std::string::npos)o.push_back(c);return o;}
System0040::System0040(std::string root):requirements(std::move(root)){}
AuditReport System0040::audit()const{AuditReport r;r.prompt_count=requirements.specs().size();for(auto&c:requirements.coverage()){r.phase_prompts[c.major]=c.prompts;if(!c.implemented)r.issues.push_back("phase "+std::to_string(c.major)+": missing specification index");}r.ready=r.issues.empty()&&requirements.complete_0_40();return r;}
HealthAssessment HealthEngine::assess(const std::string&sub,const std::vector<HealthSignal>&xs)const{HealthAssessment a{sub,"healthy",1.0,{}};for(auto&x:xs){if(x.subsystem!=sub)continue;if(x.critical>0&&x.value>=x.critical){a.score=std::min(a.score,0.2);a.state="critical";a.reasons.push_back(x.metric+" critical");}else if(x.warn>0&&x.value>=x.warn){a.score=std::min(a.score,0.6);if(a.state!="critical")a.state="degraded";a.reasons.push_back(x.metric+" warning");}}return a;}
std::vector<std::vector<TimelineEvent>> EventCorrelator::correlate(std::vector<TimelineEvent>v,std::chrono::seconds w)const{std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.at<b.at;});std::vector<std::vector<TimelineEvent>>o;for(auto&e:v){if(o.empty()||e.at-o.back().back().at>w)o.push_back({e});else o.back().push_back(e);}return o;}
std::string SecretRedactor::redact(std::string s)const{static const std::regex patterns[] = {std::regex(R"((password|passwd|token|secret|api[_-]?key)\s*[:=]\s*([^\s,;]+))",std::regex::icase),std::regex(R"((Bearer)\s+[A-Za-z0-9._~+/-]+=*)",std::regex::icase)};for(auto&r:patterns)s=std::regex_replace(s,r,"$1=<redacted>");return s;}
Fields SecretRedactor::redact(Fields f)const{for(auto&[k,v]:f){auto x=lower(k);if(x.find("password")!=std::string::npos||x.find("token")!=std::string::npos||x.find("secret")!=std::string::npos||x.find("key")!=std::string::npos)v="<redacted>";else v=redact(v);}return f;}
FileTransactionResult ConfigurationTransaction::apply(const std::string&path,const std::string&content,bool confirmed)const{if(!confirmed)return{false,"","confirmation required"};fs::path p(path);std::error_code ec;if(!p.has_filename())return{false,"","invalid target"};auto parent=p.parent_path();if(parent.empty())parent=".";if(!fs::exists(parent,ec))return{false,"","parent missing"};std::string backup;if(fs::exists(p,ec)){backup=path+".rebuntu.bak";fs::copy_file(p,backup,fs::copy_options::overwrite_existing,ec);if(ec)return{false,"","backup failed: "+ec.message()};}auto tmp=path+".rebuntu.tmp."+std::to_string(::getpid());{std::ofstream f(tmp,std::ios::binary|std::ios::trunc);if(!f)return{false,backup,"temporary write failed"};f<<content;f.flush();if(!f)return{false,backup,"temporary flush failed"};}fs::rename(tmp,p,ec);if(ec){fs::remove(tmp);return{false,backup,"atomic rename failed: "+ec.message()};}return{true,backup,{}};}
bool ConfigurationTransaction::rollback(const std::string&path,const std::string&backup)const{if(backup.empty())return false;std::error_code ec;fs::copy_file(backup,path,fs::copy_options::overwrite_existing,ec);return !ec;}

}
