#include <runtime/phases_40_45.hpp>
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <queue>
#include <regex>
#include <stdexcept>
namespace fs=std::filesystem; namespace rebuntu::platform::v4045 {
void SearchSystem::add_provider(std::string n,Provider p){if(n.empty()||!p)throw std::invalid_argument("provider");providers_[std::move(n)]=std::move(p);} 
std::vector<std::string> SearchSystem::providers()const{std::vector<std::string>r;for(auto&[n,_]:providers_)r.push_back(n);return r;}
std::vector<SearchResult> SearchSystem::search(const Query&q)const{std::vector<SearchResult>r;for(auto&[name,p]:providers_){if(!q.domains.empty()&&!q.domains.count(name))continue;try{auto x=p(q);for(auto&v:x){if(v.domain.empty())v.domain=name;if(std::isnan(v.score)||std::isinf(v.score))v.score=0;r.push_back(std::move(v));}}catch(...){}}std::stable_sort(r.begin(),r.end(),[](auto&a,auto&b){if(a.score!=b.score)return a.score>b.score;return a.id<b.id;});std::set<std::pair<std::string,std::string>>seen;r.erase(std::remove_if(r.begin(),r.end(),[&](auto&x){return !seen.emplace(x.domain,x.id).second;}),r.end());if(r.size()>q.limit)r.resize(q.limit);return r;}
bool WorkflowSystem::define(std::string id,std::vector<WorkflowNode> n){if(id.empty()||n.empty())return false;std::set<std::string>ids;for(auto&x:n)if(x.id.empty()||!ids.insert(x.id).second)return false;for(auto&x:n)for(auto&d:x.after)if(!ids.count(d))return false;defs_[std::move(id)]=std::move(n);return true;}
WorkflowRun WorkflowSystem::run(const std::string&id){WorkflowRun r{id+"#"+std::to_string(++seq_),RunState::running};auto it=defs_.find(id);if(it==defs_.end()){r.state=RunState::failed;r.failed.push_back("definition-not-found");return r;}std::set<std::string>done;bool progress=true;while(done.size()<it->second.size()&&progress){progress=false;for(auto&n:it->second){if(done.count(n.id))continue;bool ready=std::all_of(n.after.begin(),n.after.end(),[&](auto&d){return done.count(d);});if(!ready)continue;bool ok=false;for(unsigned a=0;a<=n.retries&&!ok;a++)try{ok=n.action?n.action():false;}catch(...){ok=false;}if(!ok){r.failed.push_back(n.id);r.state=RunState::failed;runs_[r.id]=r;return r;}done.insert(n.id);r.completed.push_back(n.id);progress=true;}}r.state=done.size()==it->second.size()?RunState::succeeded:RunState::failed;if(r.state==RunState::failed)r.failed.push_back("dependency-cycle");runs_[r.id]=r;return r;}
std::optional<WorkflowRun> WorkflowSystem::status(const std::string&id)const{auto i=runs_.find(id);return i==runs_.end()?std::optional<WorkflowRun>{}:i->second;}
bool KnowledgeGraph::upsert(GraphNode n){if(n.id.empty()||n.type.empty())return false;nodes_[n.id]=std::move(n);return true;}bool KnowledgeGraph::relate(GraphEdge e){if(!nodes_.count(e.from)||!nodes_.count(e.to)||e.type.empty())return false;edges_.push_back(std::move(e));return true;}
std::optional<GraphNode> KnowledgeGraph::get(const std::string&id)const{auto i=nodes_.find(id);return i==nodes_.end()?std::optional<GraphNode>{}:i->second;}
std::vector<GraphNode> KnowledgeGraph::neighbors(const std::string&id,const std::string&type)const{std::vector<GraphNode>r;for(auto&e:edges_)if((type.empty()||e.type==type)&&(e.from==id||e.to==id)){auto n=e.from==id?e.to:e.from;if(auto i=nodes_.find(n);i!=nodes_.end())r.push_back(i->second);}return r;}
std::vector<std::string> KnowledgeGraph::path(const std::string&a,const std::string&b,std::size_t max)const{if(!nodes_.count(a)||!nodes_.count(b))return{};std::queue<std::vector<std::string>>q;q.push({a});std::set<std::string>seen{a};while(!q.empty()){auto p=q.front();q.pop();if(p.back()==b)return p;if(p.size()>max)continue;for(auto&n:neighbors(p.back()))if(seen.insert(n.id).second){auto x=p;x.push_back(n.id);q.push(std::move(x));}}return{};}
Recommendation OperatorIntelligence::diagnose(std::string subject,const std::vector<Evidence>&e)const{Recommendation r{"diag:"+subject,"Evidence-grounded assessment for "+subject,0,e,{},false};if(e.empty())return r;double s=0;for(auto&x:e)s+=std::clamp(x.confidence,0.0,1.0);r.confidence=s/e.size();r.actionable=r.confidence>=0.65;r.expected_effects["evidence_count"]=std::to_string(e.size());return r;}
std::vector<Recommendation> OperatorIntelligence::rank(std::vector<Recommendation>r)const{std::stable_sort(r.begin(),r.end(),[](auto&a,auto&b){return a.confidence>b.confidence;});return r;}
void AdaptiveWorkstation::protect(std::string t){protected_.insert(std::move(t));}bool AdaptiveWorkstation::propose(Adaptation a){if(a.id.empty()||a.target.empty()||protected_.count(a.target)||!a.reversible)return false;proposed_[a.id]=std::move(a);return true;}bool AdaptiveWorkstation::authorize(const std::string&id,bool ok){auto i=proposed_.find(id);if(i==proposed_.end()||(!ok&&(i->second.privileged||i->second.expected_gain<0)))return false;if(ok)authorized_.insert(id);return ok;}bool AdaptiveWorkstation::apply(const std::string&id){auto i=proposed_.find(id);if(i==proposed_.end()||!authorized_.count(id))return false;applied_[id]=i->second;return true;}bool AdaptiveWorkstation::rollback(const std::string&id){auto i=applied_.find(id);if(i==applied_.end()||!i->second.reversible)return false;applied_.erase(i);return true;}std::optional<Adaptation> AdaptiveWorkstation::current(const std::string&id)const{auto i=applied_.find(id);return i==applied_.end()?std::optional<Adaptation>{}:i->second;}
UnifiedControlPlane::UnifiedControlPlane(){for(int m=30;m<=39;m++){v3039::LinuxDomain d(m);search.add_provider(d.name(),[d](const Query&q){std::vector<SearchResult>r;for(auto&o:d.discover()){if(!q.text.empty()&&o.id.find(q.text)==std::string::npos&&o.kind.find(q.text)==std::string::npos)continue;r.push_back({o.id,d.name(),o.kind+": "+o.id,1.0,o.attributes,{}});}return r;});}}
Operation UnifiedControlPlane::plan(std::string d,std::string a,std::string t,Fields f,bool m,bool p,bool x){Operation o{"op-"+std::to_string(++seq_),std::move(d),std::move(a),std::move(t),std::move(f),m,p,x};o.journal.push_back("planned");return o;}
bool UnifiedControlPlane::validate(Operation&o){if(o.domain.empty()||o.action.empty()||o.target.empty()){o.state=OperationState::rejected;o.journal.push_back("validation:missing-fields");return false;}o.state=OperationState::validated;o.journal.push_back("validated");return true;}
bool UnifiedControlPlane::authorize(Operation&o,bool approved){if(o.state!=OperationState::validated)return false;if((o.mutating||o.privileged||o.destructive)&&!approved){o.state=OperationState::rejected;o.journal.push_back("authorization:operator-required");return false;}o.state=OperationState::authorized;o.journal.push_back("authorized");return true;}
bool UnifiedControlPlane::execute(Operation&o){if(o.state!=OperationState::authorized)return false;o.state=OperationState::executing;o.journal.push_back("executed:typed-boundary");history_.push_back(o);return true;}bool UnifiedControlPlane::verify(Operation&o){if(o.state!=OperationState::executing)return false;o.state=OperationState::verified;o.journal.push_back("verified");if(!history_.empty()&&history_.back().id==o.id)history_.back()=o;return true;}bool UnifiedControlPlane::rollback(Operation&o){if(o.state!=OperationState::executing&&o.state!=OperationState::verified)return false;o.state=OperationState::rolled_back;o.journal.push_back("rolled-back");if(!history_.empty()&&history_.back().id==o.id)history_.back()=o;return true;}std::vector<Operation> UnifiedControlPlane::history()const{return history_;}
PhaseRegistry::PhaseRegistry(std::string root){std::regex re(R"((4[0-5])\.(\d+)[-_](.+)\.md$)");std::error_code ec;if(!fs::exists(root,ec))return;for(auto const&e:fs::recursive_directory_iterator(root,ec)){if(!e.is_regular_file())continue;std::smatch m;auto n=e.path().filename().string();if(std::regex_match(n,m,re)){std::string t=m[3];std::replace(t.begin(),t.end(),'-',' ');phases_.push_back({std::stoi(m[1]),std::stoi(m[2]),t,e.path().string()});}}std::sort(phases_.begin(),phases_.end(),[](auto&a,auto&b){return std::tie(a.major,a.minor)<std::tie(b.major,b.minor);});phases_.erase(std::unique(phases_.begin(),phases_.end(),[](auto&a,auto&b){return a.major==b.major&&a.minor==b.minor;}),phases_.end());}
std::size_t PhaseRegistry::count(int m)const{return std::count_if(phases_.begin(),phases_.end(),[&](auto&p){return p.major==m;});}bool PhaseRegistry::complete()const{const std::map<int,std::size_t>w{{40,80},{41,124},{42,120},{43,231},{44,320},{45,353}};for(auto&[m,n]:w)if(count(m)!=n)return false;return true;}
}
