#!/usr/bin/env bash
# Regenerate the canonical repository tree: __tree__.txt
# Excludes generated/irrelevant directories. Safe: only writes __tree__.txt.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
{
  echo "# Rebuntu — canonical repository tree (Phase 0.0)"
  echo "# Regenerated by scripts/generate_tree.sh. An architectural aid, not"
  echo "# implementation truth. Directories are not capabilities."
  echo
  find . \
    -name .git -prune -o \
    -name .phases -prune -o \
    -name build -prune -o \
    -name .venv -prune -o \
    -name venv -prune -o \
    -name __pycache__ -prune -o \
    -type f -print -o \
    -type d -print \
  | sed -e 's|^\./||' -e 's|[^/]*/|  |g' | sort
} > __tree__.txt
echo "wrote __tree__.txt ($(wc -l < __tree__.txt) lines)"
