#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, re, sys
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'src'
MARKER='behavioral_implementation = false'
created=[]; preserved=[]; candidates=[]
for h in sorted(SRC.rglob('types.hpp')):
    try: text=h.read_text()
    except UnicodeDecodeError: continue
    if MARKER not in text or 'namespace rebuntu::skeleton::' not in text:
        continue
    candidates.append(h)
    cpp=h.with_suffix('.cpp')
    relh=h.relative_to(ROOT).as_posix()
    relcpp=cpp.relative_to(ROOT).as_posix()
    if cpp.exists() and cpp.read_text().strip():
        preserved.append(relcpp); continue
    digest=hashlib.sha256(relh.encode()).hexdigest()[:16]
    symbol='rebuntu_structural_translation_unit_anchor_'+digest
    body=f'''// Generated structural translation-unit scaffold.\n// No behavioral maturity credit: this file only materializes the C++ ownership boundary.\n#include "{h.relative_to(SRC).as_posix()}"\n\n#include <string_view>\n\nnamespace rebuntu::structural_translation_units {{\n[[nodiscard]] std::string_view {symbol}() noexcept {{\n    return "{relh}";\n}}\n}}  // namespace rebuntu::structural_translation_units\n'''
    cpp.write_text(body)
    created.append(relcpp)
report={
 'pass':'XXIV translation-unit skeleton oversaturation',
 'policy':'structural-only; generated .cpp files do not constitute behavioral implementation evidence',
 'candidate_skeleton_headers':len(candidates),
 'created_cpp':len(created),
 'preserved_existing_cpp':len(preserved),
 'created':created,
 'preserved':preserved,
}
out=ROOT/'docs/reports/translation_unit_saturation_xxiv.json'
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(json.dumps(report,indent=2)+'\n')
md=ROOT/'docs/reports/translation_unit_saturation_xxiv.md'
md.write_text(f'''# XXIV — Translation Unit Skeleton Oversaturation\n\nThis pass materializes `.cpp` translation-unit scaffolding for structural `types.hpp` leaves generated by the structural saturation system.\n\n- Candidate structural headers: **{len(candidates)}**\n- Newly created `.cpp`: **{len(created)}**\n- Existing non-empty `.cpp` preserved: **{len(preserved)}**\n- Maturity credit: **none**\n\nThe generated translation units intentionally contain no Linux mechanism implementation and no fake domain behavior. They establish compile-visible ownership points for later evidence-driven implementation passes. Native Linux remains authoritative.\n''')
print(json.dumps({k:report[k] for k in ('candidate_skeleton_headers','created_cpp','preserved_existing_cpp')}))
