// rebuntu::runtime::preferences::io — Preferences File I/O Implementation (Phase 1.7)
//
// This provides file-based persistence for preferences using native Linux
// configuration mechanisms: XDG Base Directory, environment.d.

#include "runtime/preferences/io.hpp"
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <optional>

// environ is declared in <cstdlib> on some systems, but we need to include it
#if defined(__linux__) || defined(__APPLE__)
extern "C" { extern char** environ; }
#endif

namespace rebuntu::runtime::preferences {

// ============================================================================
// PreferenceStorage Implementation
// ============================================================================

std::map<std::string, PreferenceValue> 
PreferenceStorage::load_preferences() const {
    std::map<std::string, PreferenceValue> all_values;
    
    // Load system preferences first (lower precedence)
    auto sys_result = parse_preference_file(system_prefs_path());
    for (const auto& [id, value] : sys_result) {
        if (all_values.find(id) == all_values.end()) {
            all_values[id] = value;
        }
    }
    
    // Load user preferences (higher precedence - overrides system)
    auto user_result = parse_preference_file(user_prefs_path());
    for (const auto& [id, value] : user_result) {
        all_values[id] = value;  // User values always override
    }
    
    return all_values;
}

bool PreferenceStorage::save_preferences(const std::map<std::string, PreferenceValue>& values) const {
    // Create directory if it doesn't exist
    std::error_code ec;
    std::filesystem::create_directories(paths_.user_config_dir, ec);
    if (ec) {
        return false;  // Failed to create directory
    }
    
    // Write user preferences
    std::ofstream out(user_prefs_path());
    if (!out) {
        return false;  // Failed to open file for writing
    }
    
    // Write header
    out << "# Rebuntu Preferences - User Configuration\n";
    out << "# Generated by Rebuntu " << __DATE__ << "\n\n";
    
    // Write each preference in TOML-like format
    for (const auto& [id, value] : values) {
        if (!value.is_default && value.source == PreferenceValue::Source::kUserConfig) {
            out << "[" << id << "]\n";
            out << "value = \"" << value.selected_value << "\"\n";
            out << "scope = \"" << to_string(value.scope) << "\"\n";
            if (value.satisfaction_status != PreferenceSatisfaction::UNKNOWN) {
                out << "satisfaction = \"" << to_string(value.satisfaction_status) << "\"\n";
            }
            out << "\n";
        }
    }
    
    out.close();
    return true;
}

std::vector<PreferenceValue> PreferenceStorage::load_environment_d() const {
    std::vector<PreferenceValue> env_values;
    
    // Check if environment.d directory exists
    if (!std::filesystem::exists(paths_.env_d_dir)) {
        return env_values;  // Empty vector, not an error
    }
    
    // Load all .conf files from /etc/environment.d/
    for (const auto& entry : std::filesystem::directory_iterator(paths_.env_d_dir)) {
        if (entry.is_regular_file() && 
            entry.path().extension() == ".conf") {
            
            std::ifstream in(entry.path());
            if (!in) continue;
            
            std::string line;
            while (std::getline(in, line)) {
                // Skip comments and empty lines
                if (line.empty() || line[0] == '#') continue;
                
                // Parse REBUNTU_PREFERENCE_<ID>=<value> format
                size_t eq_pos = line.find('=');
                if (eq_pos == std::string::npos) continue;
                
                std::string key = line.substr(0, eq_pos);
                std::string value = line.substr(eq_pos + 1);
                
                // Remove quotes from value
                if (!value.empty() && value.front() == '"' && value.back() == '"') {
                    value = value.substr(1, value.size() - 2);
                }
                
                // Check if this is a Rebuntu preference
                std::string prefix = "REBUNTU_PREFERENCE_";
                if (key.substr(0, prefix.size()) == prefix) {
                    PreferenceValue pv;
                    pv.id = key.substr(prefix.size());
                    pv.selected_value = value;
                    pv.scope = PreferenceScope::kUser;
                    pv.source = PreferenceValue::Source::kEnvironment;
                    env_values.push_back(pv);
                }
            }
        }
    }
    
    return env_values;
}

std::map<std::string, PreferenceValue> 
PreferenceStorage::parse_preference_file(const std::filesystem::path& path) const {
    std::map<std::string, PreferenceValue> values;
    
    if (!std::filesystem::exists(path)) {
        return values;  // Empty map, not an error
    }
    
    std::ifstream in(path);
    if (!in) return values;
    
    std::string line;
    std::optional<PreferenceValue> current_value;
    std::string current_id;
    
    while (std::getline(in, line)) {
        // Trim whitespace
        size_t first = line.find_first_not_of(" \t\r\n");
        if (first == std::string::npos) continue;
        size_t last = line.find_last_not_of(" \t\r\n");
        line = line.substr(first, last - first + 1);
        
        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') continue;
        
        // Parse section headers like [id]
        if (line.front() == '[' && line.back() == ']') {
            // Save previous value if exists
            if (current_value.has_value()) {
                values[current_id] = *current_value;
            }
            
            // Start new section
            current_id = line.substr(1, line.size() - 2);
            current_value.emplace();
            current_value->id = current_id;
        }
        // Parse key = value pairs
        else if (current_value.has_value()) {
            size_t eq_pos = line.find('=');
            if (eq_pos == std::string::npos) continue;
            
            std::string key = line.substr(0, eq_pos);
            std::string val = line.substr(eq_pos + 1);
            
            // Trim key and value
            size_t k_first = key.find_first_not_of(" \t");
            size_t k_last = key.find_last_not_of(" \t");
            key = (k_first != std::string::npos) ? key.substr(k_first, k_last - k_first + 1) : "";
            
            size_t v_first = val.find_first_not_of(" \t\"");
            size_t v_last = val.find_last_not_of(" \t\"");
            val = (v_first != std::string::npos) ? val.substr(v_first, v_last - v_first + 1) : "";
            
            // Remove surrounding quotes if present
            if (!val.empty() && val.front() == '"' && val.back() == '"') {
                val = val.substr(1, val.size() - 2);
            }
            
            if (key == "value") {
                current_value->selected_value = val;
                current_value->source = PreferenceValue::Source::kUserConfig;
            } else if (key == "scope") {
                if (val == "system") current_value->scope = PreferenceScope::kSystem;
                else if (val == "user") current_value->scope = PreferenceScope::kUser;
                else if (val == "session") current_value->scope = PreferenceScope::kSession;
            } else if (key == "satisfaction") {
                if (val == "satisfied") current_value->satisfaction_status = PreferenceSatisfaction::SATISFIED;
                else if (val == "unsatisfied") current_value->satisfaction_status = PreferenceSatisfaction::UNSATISFIED;
                else if (val == "not_applicable") current_value->satisfaction_status = PreferenceSatisfaction::NOT_APPLICABLE;
            }
        }
    }
    
    // Save last value
    if (current_value.has_value()) {
        values[current_id] = *current_value;
    }
    
    return values;
}

// ============================================================================
// EnvironmentPreferenceResolver Implementation
// ============================================================================

std::map<std::string, PreferenceValue> 
EnvironmentPreferenceResolver::resolve_from_environment() {
    std::map<std::string, PreferenceValue> prefs;
    
    // Check for REBUNTU_PREFERENCE_* environment variables
    for (char** env = environ; *env != nullptr; ++env) {
        std::string entry(*env);
        
        // Look for REBUNTU_PREFERENCE_<ID>=VALUE format
        size_t pos = entry.find("REBUNTU_PREFERENCE_");
        if (pos == 0) {
            size_t eq_pos = entry.find('=');
            if (eq_pos != std::string::npos) {
                std::string id = entry.substr(19, eq_pos - 19);  // 19 = len("REBUNTU_PREFERENCE_")
                std::string value = entry.substr(eq_pos + 1);
                
                PreferenceValue pv;
                pv.id = id;
                pv.selected_value = value;
                pv.scope = PreferenceScope::kSession;  // Environment vars are session-scoped
                pv.source = PreferenceValue::Source::kEnvironment;
                
                prefs[id] = std::move(pv);
            }
        }
    }
    
    return prefs;
}

std::optional<PreferenceValue> 
EnvironmentPreferenceResolver::get_env_preference(std::string_view pref_id) {
    std::string var_name = "REBUNTU_PREFERENCE_" + std::string{pref_id};
    const char* value = std::getenv(var_name.c_str());
    
    if (value == nullptr) return std::nullopt;
    
    PreferenceValue pv;
    pv.id = std::string{pref_id};
    pv.selected_value = value;
    pv.scope = PreferenceScope::kSession;
    pv.source = PreferenceValue::Source::kEnvironment;
    
    return pv;
}

// ============================================================================
// SessionPreferences Implementation
// ============================================================================

std::map<std::string, PreferenceValue> 
SessionPreferences::load() const {
    // For now, session preferences are just the in-memory values
    return session_values_;
}

void SessionPreferences::set(std::string id, std::string value) {
    session_values_[id].id = std::move(id);
    session_values_[id].selected_value = std::move(value);
    session_values_[id].scope = PreferenceScope::kSession;
    session_values_[id].source = PreferenceValue::Source::kInvocation;  // Session override
}

void SessionPreferences::clear() {
    session_values_.clear();
}

std::map<std::string, PreferenceValue> 
SessionPreferences::get_all() const {
    return session_values_;
}

}  // namespace rebuntu::runtime::preferences